run:
  tests: true

linters:
  enable-all: true
  disable:
    - errcheck
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gosec
    - lll
    - maligned
    - unparam
    - stylecheck
    - funlen
    - wsl

linters-settings:
  goimports:
    local-prefixes: github.com/stripe/stripe-cli
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
  exclude-use-default: false
