run:
  tests: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - exportloopref
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - revive
    # - rowserrcheck -- disabled because of https://github.com/golangci/golangci-lint/issues/2649
    - staticcheck
    # - structcheck -- disabled because of https://github.com/golangci/golangci-lint/issues/2649
    - typecheck
    - unconvert
    - unused
    - varcheck
    - whitespace

linters-settings:
  goimports:
    local-prefixes: github.com/stripe/stripe-cli
  misspell:
    locale: US

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
