run:
  tests: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    # - revive -- TODO: reenable after fixing errors
    # - rowserrcheck -- disabled because of https://github.com/golangci/golangci-lint/issues/2649
    - staticcheck
    # - structcheck -- disabled because of https://github.com/golangci/golangci-lint/issues/2649
    - typecheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  depguard:
    rules:
      main:
        list-mode: lax
        allow:
          - $all
        deny: []
  goimports:
    local-prefixes: github.com/stripe/stripe-cli
  govet:
    disable:
      - printf
  misspell:
    locale: US
  staticcheck:
    checks:
      - all
      - -SA1006
      - -SA1019

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
