project_name: stripe
builds:
  - main: ./cmd/stripe/main.go
    env:
      - CGO_ENABLED=0
      - GO111MODULE=on
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w -X github.com/stripe/stripe-cli/pkg/version.Version={{.Version}}
archives:
  -
    replacements:
      darwin: mac-os
      linux: linux
      windows: windows
      amd64: x86_64
    files:
    - none*
checksum:
  name_template: '{{ .ProjectName }}-checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpms:
  -
    vendor: Stripe
    homepage:  https://stripe.com
    maintainer: Stripe <support@stripe.com>
    description: Stripe CLI utility
    license: Apache 2.0
    formats:
    - deb
    - rpm
brews:
  -
    github:
      owner: stripe
      name: homebrew-stripe-cli
    commit_author:
      name: stripe-ci
      email: support@stripe.com
    homepage:  https://stripe.com
    description: Stripe CLI utility
    install: |
      bin.install "stripe"
      rm Dir["#{bin}/{stripe-completion.bash,stripe-completion.zsh}"]
      system bin/"stripe", "completion"
      system bin/"stripe", "completion", "--shell", "zsh"
      bash_completion.install "stripe-completion.bash"
      zsh_completion.install "stripe-completion.zsh"
      (zsh_completion/"_stripe").write <<~EOS
        #compdef stripe
        _stripe () {
          local e
          e=$(dirname ${funcsourcetrace[1]%:*})/stripe-completion.zsh
          if [[ -f $e ]]; then source $e; fi
        }
      EOS
scoop:
  bucket:
    owner: stripe
    name: scoop-stripe-cli
  commit_author:
    name: stripe-ci
    email: support@stripe.com
  homepage:  https://stripe.com
  description: Stripe CLI utility
  license: Apache 2.0
