dist: bionic

language: go

go: '1.12.x'

addons:
  apt:
    packages:
    - rpm

install:
  - make setup

script:
  - make ci

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
  verbose: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: script
  skip_cleanup: true
  script: bash scripts/publish-deb-to-bintray.sh
  verbose: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: script
  skip_cleanup: true
  script: bash scripts/publish-rpm-to-bintray.sh
  verbose: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
