dist: bionic

language: go

go: '1.14.x'

addons:
  apt:
    packages:
    - rpm

services:
  - docker

install:
  - make setup

script:
  - travis_retry make ci

deploy:
- provider: script
  skip_cleanup: true
  # We're running GoReleaser using the mailchain/goreleaser-xcgo Docker image
  # so we can use cgo when building the binaries for all platforms.
  # See https://github.com/stripe/stripe-cli/pull/439 and
  # https://github.com/goreleaser/goreleaser/issues/708#issuecomment-488779914
  script: docker run -e DOCKER_USERNAME=$DOCKER_USERNAME -e DOCKER_PASSWORD=$DOCKER_PASSWORD -e GITHUB_TOKEN=$GITHUB_TOKEN --rm --privileged -v $TRAVIS_BUILD_DIR:/go/src/github.com/stripe/stripe-cli -v /var/run/docker.sock:/var/run/docker.sock -w /go/src/github.com/stripe/stripe-cli mailchain/goreleaser-xcgo --rm-dist
  verbose: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: script
  skip_cleanup: true
  script: bash scripts/publish-deb-to-bintray.sh
  verbose: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: script
  skip_cleanup: true
  script: bash scripts/publish-rpm-to-bintray.sh
  verbose: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: script
  skip_cleanup: true
  script: bash scripts/upload-zip-to-virustotal.sh
  verbose: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
