dist: bionic

language: go

go: '1.14.x'

addons:
  apt:
    packages:
    - rpm

services:
  - docker

install:
  - make setup

script:
  - make ci

after_success:
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
  verbose: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: script
  skip_cleanup: true
  script: bash scripts/publish-deb-to-bintray.sh
  verbose: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: script
  skip_cleanup: true
  script: bash scripts/publish-rpm-to-bintray.sh
  verbose: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
- provider: script
  skip_cleanup: true
  script: bash scripts/upload-zip-to-virustotal.sh
  verbose: true
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
