language: go

go:
- 1.12.x

addons:
  apt:
    packages:
    - rpm

env:
- GO111MODULE=on

install:
  - make install-deps
  - go mod download

deploy:
- provider: script
  skip_cleanup: true
  script: ./travis-goreleaser
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
