[[Plugin]]
  Shortname = "preview"
  Shortdesc = ""
  Binary = "stripe-cli-preview"
  MagicCookieValue = "F3A8FE09-713E-4F95-8767-2A5A9CFC6368"

  [[Plugin.Release]]
    Arch = "amd64"
    OS = "darwin"
    Version = "0.10.2"
    Sum = "39931649f9b585797b8a30f2c5c229f269c2bffd64de707cb267fa3ee013b1bc"

  [[Plugin.Release]]
    Arch = "arm64"
    OS = "darwin"
    Version = "0.10.2"
    Sum = "39931649f9b585797b8a30f2c5c229f269c2bffd64de707cb267fa3ee013b1bc"
