// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: events_resend.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventsResendRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the event to resend.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Resend the event to the given Stripe account. This is useful when testing a Connect platform.
	Account string `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	// Additional data to send with an API request. Supports setting nested values
	// (e.g nested[param]=value).
	Data []string `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	// Response attributes to expand inline (target nested values with nested[param]=value).
	Expand []string `protobuf:"bytes,4,rep,name=expand,proto3" json:"expand,omitempty"`
	// Set an idempotency key for the request, preventing the same request from replaying within 24
	// hours.
	Idempotency string `protobuf:"bytes,5,opt,name=idempotency,proto3" json:"idempotency,omitempty"`
	// Make a live request (by default, runs in test mode).
	Live bool `protobuf:"varint,6,opt,name=live,proto3" json:"live,omitempty"`
	// Specify the Stripe account to use for this request.
	StripeAccount string `protobuf:"bytes,7,opt,name=stripe_account,json=stripeAccount,proto3" json:"stripe_account,omitempty"`
	// Specify the Stripe API version to use for this request.
	Version string `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	// Resend the event to the given webhook endpoint ID.
	WebhookEndpoint string `protobuf:"bytes,9,opt,name=webhook_endpoint,json=webhookEndpoint,proto3" json:"webhook_endpoint,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EventsResendRequest) Reset() {
	*x = EventsResendRequest{}
	mi := &file_events_resend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsResendRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResendRequest) ProtoMessage() {}

func (x *EventsResendRequest) ProtoReflect() protoreflect.Message {
	mi := &file_events_resend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResendRequest.ProtoReflect.Descriptor instead.
func (*EventsResendRequest) Descriptor() ([]byte, []int) {
	return file_events_resend_proto_rawDescGZIP(), []int{0}
}

func (x *EventsResendRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EventsResendRequest) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *EventsResendRequest) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *EventsResendRequest) GetExpand() []string {
	if x != nil {
		return x.Expand
	}
	return nil
}

func (x *EventsResendRequest) GetIdempotency() string {
	if x != nil {
		return x.Idempotency
	}
	return ""
}

func (x *EventsResendRequest) GetLive() bool {
	if x != nil {
		return x.Live
	}
	return false
}

func (x *EventsResendRequest) GetStripeAccount() string {
	if x != nil {
		return x.StripeAccount
	}
	return ""
}

func (x *EventsResendRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *EventsResendRequest) GetWebhookEndpoint() string {
	if x != nil {
		return x.WebhookEndpoint
	}
	return ""
}

type EventsResendResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StripeEvent   *StripeEvent           `protobuf:"bytes,1,opt,name=stripe_event,json=stripeEvent,proto3" json:"stripe_event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventsResendResponse) Reset() {
	*x = EventsResendResponse{}
	mi := &file_events_resend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventsResendResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventsResendResponse) ProtoMessage() {}

func (x *EventsResendResponse) ProtoReflect() protoreflect.Message {
	mi := &file_events_resend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventsResendResponse.ProtoReflect.Descriptor instead.
func (*EventsResendResponse) Descriptor() ([]byte, []int) {
	return file_events_resend_proto_rawDescGZIP(), []int{1}
}

func (x *EventsResendResponse) GetStripeEvent() *StripeEvent {
	if x != nil {
		return x.StripeEvent
	}
	return nil
}

var File_events_resend_proto protoreflect.FileDescriptor

const file_events_resend_proto_rawDesc = "" +
	"\n" +
	"\x13events_resend.proto\x12\x03rpc\x1a\fcommon.proto\"\x98\x02\n" +
	"\x13EventsResendRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12\x12\n" +
	"\x04data\x18\x03 \x03(\tR\x04data\x12\x16\n" +
	"\x06expand\x18\x04 \x03(\tR\x06expand\x12 \n" +
	"\vidempotency\x18\x05 \x01(\tR\vidempotency\x12\x12\n" +
	"\x04live\x18\x06 \x01(\bR\x04live\x12%\n" +
	"\x0estripe_account\x18\a \x01(\tR\rstripeAccount\x12\x18\n" +
	"\aversion\x18\b \x01(\tR\aversion\x12)\n" +
	"\x10webhook_endpoint\x18\t \x01(\tR\x0fwebhookEndpoint\"K\n" +
	"\x14EventsResendResponse\x123\n" +
	"\fstripe_event\x18\x01 \x01(\v2\x10.rpc.StripeEventR\vstripeEventB\"Z github.com/stripe/stripe-cli/rpcb\x06proto3"

var (
	file_events_resend_proto_rawDescOnce sync.Once
	file_events_resend_proto_rawDescData []byte
)

func file_events_resend_proto_rawDescGZIP() []byte {
	file_events_resend_proto_rawDescOnce.Do(func() {
		file_events_resend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_resend_proto_rawDesc), len(file_events_resend_proto_rawDesc)))
	})
	return file_events_resend_proto_rawDescData
}

var file_events_resend_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_events_resend_proto_goTypes = []any{
	(*EventsResendRequest)(nil),  // 0: rpc.EventsResendRequest
	(*EventsResendResponse)(nil), // 1: rpc.EventsResendResponse
	(*StripeEvent)(nil),          // 2: rpc.StripeEvent
}
var file_events_resend_proto_depIdxs = []int32{
	2, // 0: rpc.EventsResendResponse.stripe_event:type_name -> rpc.StripeEvent
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_events_resend_proto_init() }
func file_events_resend_proto_init() {
	if File_events_resend_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_resend_proto_rawDesc), len(file_events_resend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_resend_proto_goTypes,
		DependencyIndexes: file_events_resend_proto_depIdxs,
		MessageInfos:      file_events_resend_proto_msgTypes,
	}.Build()
	File_events_resend_proto = out.File
	file_events_resend_proto_goTypes = nil
	file_events_resend_proto_depIdxs = nil
}
