// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: fixtures.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FixtureRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An event to get the default fixture for
	Event         string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixtureRequest) Reset() {
	*x = FixtureRequest{}
	mi := &file_fixtures_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixtureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixtureRequest) ProtoMessage() {}

func (x *FixtureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixtureRequest.ProtoReflect.Descriptor instead.
func (*FixtureRequest) Descriptor() ([]byte, []int) {
	return file_fixtures_proto_rawDescGZIP(), []int{0}
}

func (x *FixtureRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

type FixtureResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// default fixture for event
	Fixture       string `protobuf:"bytes,1,opt,name=fixture,proto3" json:"fixture,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FixtureResponse) Reset() {
	*x = FixtureResponse{}
	mi := &file_fixtures_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FixtureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FixtureResponse) ProtoMessage() {}

func (x *FixtureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fixtures_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FixtureResponse.ProtoReflect.Descriptor instead.
func (*FixtureResponse) Descriptor() ([]byte, []int) {
	return file_fixtures_proto_rawDescGZIP(), []int{1}
}

func (x *FixtureResponse) GetFixture() string {
	if x != nil {
		return x.Fixture
	}
	return ""
}

var File_fixtures_proto protoreflect.FileDescriptor

const file_fixtures_proto_rawDesc = "" +
	"\n" +
	"\x0efixtures.proto\x12\x03rpc\"&\n" +
	"\x0eFixtureRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\"+\n" +
	"\x0fFixtureResponse\x12\x18\n" +
	"\afixture\x18\x01 \x01(\tR\afixtureB\"Z github.com/stripe/stripe-cli/rpcb\x06proto3"

var (
	file_fixtures_proto_rawDescOnce sync.Once
	file_fixtures_proto_rawDescData []byte
)

func file_fixtures_proto_rawDescGZIP() []byte {
	file_fixtures_proto_rawDescOnce.Do(func() {
		file_fixtures_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fixtures_proto_rawDesc), len(file_fixtures_proto_rawDesc)))
	})
	return file_fixtures_proto_rawDescData
}

var file_fixtures_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_fixtures_proto_goTypes = []any{
	(*FixtureRequest)(nil),  // 0: rpc.FixtureRequest
	(*FixtureResponse)(nil), // 1: rpc.FixtureResponse
}
var file_fixtures_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_fixtures_proto_init() }
func file_fixtures_proto_init() {
	if File_fixtures_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fixtures_proto_rawDesc), len(file_fixtures_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fixtures_proto_goTypes,
		DependencyIndexes: file_fixtures_proto_depIdxs,
		MessageInfos:      file_fixtures_proto_msgTypes,
	}.Build()
	File_fixtures_proto = out.File
	file_fixtures_proto_goTypes = nil
	file_fixtures_proto_depIdxs = nil
}
