// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: listen.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListenResponse_State int32

const (
	ListenResponse_STATE_UNSPECIFIED  ListenResponse_State = 0
	ListenResponse_STATE_LOADING      ListenResponse_State = 1
	ListenResponse_STATE_RECONNECTING ListenResponse_State = 2
	ListenResponse_STATE_READY        ListenResponse_State = 3
	ListenResponse_STATE_DONE         ListenResponse_State = 4
)

// Enum value maps for ListenResponse_State.
var (
	ListenResponse_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_LOADING",
		2: "STATE_RECONNECTING",
		3: "STATE_READY",
		4: "STATE_DONE",
	}
	ListenResponse_State_value = map[string]int32{
		"STATE_UNSPECIFIED":  0,
		"STATE_LOADING":      1,
		"STATE_RECONNECTING": 2,
		"STATE_READY":        3,
		"STATE_DONE":         4,
	}
)

func (x ListenResponse_State) Enum() *ListenResponse_State {
	p := new(ListenResponse_State)
	*p = x
	return p
}

func (x ListenResponse_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListenResponse_State) Descriptor() protoreflect.EnumDescriptor {
	return file_listen_proto_enumTypes[0].Descriptor()
}

func (ListenResponse_State) Type() protoreflect.EnumType {
	return &file_listen_proto_enumTypes[0]
}

func (x ListenResponse_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListenResponse_State.Descriptor instead.
func (ListenResponse_State) EnumDescriptor() ([]byte, []int) {
	return file_listen_proto_rawDescGZIP(), []int{1, 0}
}

type ListenResponse_EndpointResponse_Data_HttpMethod int32

const (
	ListenResponse_EndpointResponse_Data_HTTP_METHOD_UNSPECIFIED ListenResponse_EndpointResponse_Data_HttpMethod = 0
	ListenResponse_EndpointResponse_Data_HTTP_METHOD_GET         ListenResponse_EndpointResponse_Data_HttpMethod = 1
	ListenResponse_EndpointResponse_Data_HTTP_METHOD_POST        ListenResponse_EndpointResponse_Data_HttpMethod = 2
	ListenResponse_EndpointResponse_Data_HTTP_METHOD_DELETE      ListenResponse_EndpointResponse_Data_HttpMethod = 3
)

// Enum value maps for ListenResponse_EndpointResponse_Data_HttpMethod.
var (
	ListenResponse_EndpointResponse_Data_HttpMethod_name = map[int32]string{
		0: "HTTP_METHOD_UNSPECIFIED",
		1: "HTTP_METHOD_GET",
		2: "HTTP_METHOD_POST",
		3: "HTTP_METHOD_DELETE",
	}
	ListenResponse_EndpointResponse_Data_HttpMethod_value = map[string]int32{
		"HTTP_METHOD_UNSPECIFIED": 0,
		"HTTP_METHOD_GET":         1,
		"HTTP_METHOD_POST":        2,
		"HTTP_METHOD_DELETE":      3,
	}
)

func (x ListenResponse_EndpointResponse_Data_HttpMethod) Enum() *ListenResponse_EndpointResponse_Data_HttpMethod {
	p := new(ListenResponse_EndpointResponse_Data_HttpMethod)
	*p = x
	return p
}

func (x ListenResponse_EndpointResponse_Data_HttpMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListenResponse_EndpointResponse_Data_HttpMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_listen_proto_enumTypes[1].Descriptor()
}

func (ListenResponse_EndpointResponse_Data_HttpMethod) Type() protoreflect.EnumType {
	return &file_listen_proto_enumTypes[1]
}

func (x ListenResponse_EndpointResponse_Data_HttpMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListenResponse_EndpointResponse_Data_HttpMethod.Descriptor instead.
func (ListenResponse_EndpointResponse_Data_HttpMethod) EnumDescriptor() ([]byte, []int) {
	return file_listen_proto_rawDescGZIP(), []int{1, 0, 0, 0}
}

type ListenRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of custom headers to forward for Connect
	ConnectHeaders []string `protobuf:"bytes,1,rep,name=connect_headers,json=connectHeaders,proto3" json:"connect_headers,omitempty"`
	// A list of specific events to listen for. For a list of all possible events, see:
	// https://stripe.com/docs/api/events/types (default [*])
	Events []string `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	// The URL to forward Connect webhook events to (default: same as normal events)
	ForwardConnectTo string `protobuf:"bytes,3,opt,name=forward_connect_to,json=forwardConnectTo,proto3" json:"forward_connect_to,omitempty"`
	// The URL to forward webhook events to
	ForwardTo string `protobuf:"bytes,4,opt,name=forward_to,json=forwardTo,proto3" json:"forward_to,omitempty"`
	// A list of custom headers to forward
	Headers []string `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty"`
	// Receive events formatted with the latest API version (default: your account's default API
	// version)
	Latest bool `protobuf:"varint,6,opt,name=latest,proto3" json:"latest,omitempty"`
	// Receive live events (default: test)
	Live bool `protobuf:"varint,7,opt,name=live,proto3" json:"live,omitempty"`
	// Skip certificate verification when forwarding to HTTPS endpoints
	SkipVerify bool `protobuf:"varint,8,opt,name=skip_verify,json=skipVerify,proto3" json:"skip_verify,omitempty"`
	// Load webhook endpoint configuration from the webhooks API/dashboard
	UseConfiguredWebhooks bool `protobuf:"varint,9,opt,name=use_configured_webhooks,json=useConfiguredWebhooks,proto3" json:"use_configured_webhooks,omitempty"`
	// A list of thin-type events to listen for. Defaults to none.
	ThinEvents []string `protobuf:"bytes,10,rep,name=thin_events,json=thinEvents,proto3" json:"thin_events,omitempty"`
	// The URL to forward thin webhook events to
	ForwardThinTo string `protobuf:"bytes,11,opt,name=forward_thin_to,json=forwardThinTo,proto3" json:"forward_thin_to,omitempty"`
	// The URL to forward thin Connect webhook events to (default: same as normal thin events)
	ForwardThinConnectTo string `protobuf:"bytes,12,opt,name=forward_thin_connect_to,json=forwardThinConnectTo,proto3" json:"forward_thin_connect_to,omitempty"`
	// The Stripe API version associated with the provided snapshot payload event types
	ApiVersion    string `protobuf:"bytes,13,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenRequest) Reset() {
	*x = ListenRequest{}
	mi := &file_listen_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenRequest) ProtoMessage() {}

func (x *ListenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listen_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenRequest.ProtoReflect.Descriptor instead.
func (*ListenRequest) Descriptor() ([]byte, []int) {
	return file_listen_proto_rawDescGZIP(), []int{0}
}

func (x *ListenRequest) GetConnectHeaders() []string {
	if x != nil {
		return x.ConnectHeaders
	}
	return nil
}

func (x *ListenRequest) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListenRequest) GetForwardConnectTo() string {
	if x != nil {
		return x.ForwardConnectTo
	}
	return ""
}

func (x *ListenRequest) GetForwardTo() string {
	if x != nil {
		return x.ForwardTo
	}
	return ""
}

func (x *ListenRequest) GetHeaders() []string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ListenRequest) GetLatest() bool {
	if x != nil {
		return x.Latest
	}
	return false
}

func (x *ListenRequest) GetLive() bool {
	if x != nil {
		return x.Live
	}
	return false
}

func (x *ListenRequest) GetSkipVerify() bool {
	if x != nil {
		return x.SkipVerify
	}
	return false
}

func (x *ListenRequest) GetUseConfiguredWebhooks() bool {
	if x != nil {
		return x.UseConfiguredWebhooks
	}
	return false
}

func (x *ListenRequest) GetThinEvents() []string {
	if x != nil {
		return x.ThinEvents
	}
	return nil
}

func (x *ListenRequest) GetForwardThinTo() string {
	if x != nil {
		return x.ForwardThinTo
	}
	return ""
}

func (x *ListenRequest) GetForwardThinConnectTo() string {
	if x != nil {
		return x.ForwardThinConnectTo
	}
	return ""
}

func (x *ListenRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

type ListenResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*ListenResponse_State_
	//	*ListenResponse_StripeEvent
	//	*ListenResponse_EndpointResponse_
	//	*ListenResponse_V2StripeEvent
	Content       isListenResponse_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenResponse) Reset() {
	*x = ListenResponse{}
	mi := &file_listen_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenResponse) ProtoMessage() {}

func (x *ListenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listen_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenResponse.ProtoReflect.Descriptor instead.
func (*ListenResponse) Descriptor() ([]byte, []int) {
	return file_listen_proto_rawDescGZIP(), []int{1}
}

func (x *ListenResponse) GetContent() isListenResponse_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ListenResponse) GetState() ListenResponse_State {
	if x != nil {
		if x, ok := x.Content.(*ListenResponse_State_); ok {
			return x.State
		}
	}
	return ListenResponse_STATE_UNSPECIFIED
}

func (x *ListenResponse) GetStripeEvent() *StripeEvent {
	if x != nil {
		if x, ok := x.Content.(*ListenResponse_StripeEvent); ok {
			return x.StripeEvent
		}
	}
	return nil
}

func (x *ListenResponse) GetEndpointResponse() *ListenResponse_EndpointResponse {
	if x != nil {
		if x, ok := x.Content.(*ListenResponse_EndpointResponse_); ok {
			return x.EndpointResponse
		}
	}
	return nil
}

func (x *ListenResponse) GetV2StripeEvent() *V2StripeEvent {
	if x != nil {
		if x, ok := x.Content.(*ListenResponse_V2StripeEvent); ok {
			return x.V2StripeEvent
		}
	}
	return nil
}

type isListenResponse_Content interface {
	isListenResponse_Content()
}

type ListenResponse_State_ struct {
	// Check if the stream ready
	State ListenResponse_State `protobuf:"varint,1,opt,name=state,proto3,enum=rpc.ListenResponse_State,oneof"`
}

type ListenResponse_StripeEvent struct {
	// A Stripe event
	StripeEvent *StripeEvent `protobuf:"bytes,2,opt,name=stripe_event,json=stripeEvent,proto3,oneof"`
}

type ListenResponse_EndpointResponse_ struct {
	// A response from an endpoint
	EndpointResponse *ListenResponse_EndpointResponse `protobuf:"bytes,3,opt,name=endpoint_response,json=endpointResponse,proto3,oneof"`
}

type ListenResponse_V2StripeEvent struct {
	// A V2 Stripe event
	V2StripeEvent *V2StripeEvent `protobuf:"bytes,4,opt,name=v2_stripe_event,json=v2StripeEvent,proto3,oneof"`
}

func (*ListenResponse_State_) isListenResponse_Content() {}

func (*ListenResponse_StripeEvent) isListenResponse_Content() {}

func (*ListenResponse_EndpointResponse_) isListenResponse_Content() {}

func (*ListenResponse_V2StripeEvent) isListenResponse_Content() {}

type ListenResponse_EndpointResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*ListenResponse_EndpointResponse_Data_
	//	*ListenResponse_EndpointResponse_Error
	Content       isListenResponse_EndpointResponse_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenResponse_EndpointResponse) Reset() {
	*x = ListenResponse_EndpointResponse{}
	mi := &file_listen_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenResponse_EndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenResponse_EndpointResponse) ProtoMessage() {}

func (x *ListenResponse_EndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listen_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenResponse_EndpointResponse.ProtoReflect.Descriptor instead.
func (*ListenResponse_EndpointResponse) Descriptor() ([]byte, []int) {
	return file_listen_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ListenResponse_EndpointResponse) GetContent() isListenResponse_EndpointResponse_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *ListenResponse_EndpointResponse) GetData() *ListenResponse_EndpointResponse_Data {
	if x != nil {
		if x, ok := x.Content.(*ListenResponse_EndpointResponse_Data_); ok {
			return x.Data
		}
	}
	return nil
}

func (x *ListenResponse_EndpointResponse) GetError() string {
	if x != nil {
		if x, ok := x.Content.(*ListenResponse_EndpointResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

type isListenResponse_EndpointResponse_Content interface {
	isListenResponse_EndpointResponse_Content()
}

type ListenResponse_EndpointResponse_Data_ struct {
	Data *ListenResponse_EndpointResponse_Data `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type ListenResponse_EndpointResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ListenResponse_EndpointResponse_Data_) isListenResponse_EndpointResponse_Content() {}

func (*ListenResponse_EndpointResponse_Error) isListenResponse_EndpointResponse_Content() {}

type ListenResponse_EndpointResponse_Data struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// HTTP status code
	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// HTTP method
	HttpMethod ListenResponse_EndpointResponse_Data_HttpMethod `protobuf:"varint,2,opt,name=http_method,json=httpMethod,proto3,enum=rpc.ListenResponse_EndpointResponse_Data_HttpMethod" json:"http_method,omitempty"`
	// URL of the webhook endpoint
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// ID of the Stripe event that caused this response
	EventId       string `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListenResponse_EndpointResponse_Data) Reset() {
	*x = ListenResponse_EndpointResponse_Data{}
	mi := &file_listen_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListenResponse_EndpointResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenResponse_EndpointResponse_Data) ProtoMessage() {}

func (x *ListenResponse_EndpointResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_listen_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenResponse_EndpointResponse_Data.ProtoReflect.Descriptor instead.
func (*ListenResponse_EndpointResponse_Data) Descriptor() ([]byte, []int) {
	return file_listen_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *ListenResponse_EndpointResponse_Data) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListenResponse_EndpointResponse_Data) GetHttpMethod() ListenResponse_EndpointResponse_Data_HttpMethod {
	if x != nil {
		return x.HttpMethod
	}
	return ListenResponse_EndpointResponse_Data_HTTP_METHOD_UNSPECIFIED
}

func (x *ListenResponse_EndpointResponse_Data) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ListenResponse_EndpointResponse_Data) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

var File_listen_proto protoreflect.FileDescriptor

const file_listen_proto_rawDesc = "" +
	"\n" +
	"\flisten.proto\x12\x03rpc\x1a\fcommon.proto\"\xdd\x03\n" +
	"\rListenRequest\x12'\n" +
	"\x0fconnect_headers\x18\x01 \x03(\tR\x0econnectHeaders\x12\x16\n" +
	"\x06events\x18\x02 \x03(\tR\x06events\x12,\n" +
	"\x12forward_connect_to\x18\x03 \x01(\tR\x10forwardConnectTo\x12\x1d\n" +
	"\n" +
	"forward_to\x18\x04 \x01(\tR\tforwardTo\x12\x18\n" +
	"\aheaders\x18\x05 \x03(\tR\aheaders\x12\x16\n" +
	"\x06latest\x18\x06 \x01(\bR\x06latest\x12\x12\n" +
	"\x04live\x18\a \x01(\bR\x04live\x12\x1f\n" +
	"\vskip_verify\x18\b \x01(\bR\n" +
	"skipVerify\x126\n" +
	"\x17use_configured_webhooks\x18\t \x01(\bR\x15useConfiguredWebhooks\x12\x1f\n" +
	"\vthin_events\x18\n" +
	" \x03(\tR\n" +
	"thinEvents\x12&\n" +
	"\x0fforward_thin_to\x18\v \x01(\tR\rforwardThinTo\x125\n" +
	"\x17forward_thin_connect_to\x18\f \x01(\tR\x14forwardThinConnectTo\x12\x1f\n" +
	"\vapi_version\x18\r \x01(\tR\n" +
	"apiVersion\"\x90\x06\n" +
	"\x0eListenResponse\x121\n" +
	"\x05state\x18\x01 \x01(\x0e2\x19.rpc.ListenResponse.StateH\x00R\x05state\x125\n" +
	"\fstripe_event\x18\x02 \x01(\v2\x10.rpc.StripeEventH\x00R\vstripeEvent\x12S\n" +
	"\x11endpoint_response\x18\x03 \x01(\v2$.rpc.ListenResponse.EndpointResponseH\x00R\x10endpointResponse\x12<\n" +
	"\x0fv2_stripe_event\x18\x04 \x01(\v2\x12.rpc.V2StripeEventH\x00R\rv2StripeEvent\x1a\x89\x03\n" +
	"\x10EndpointResponse\x12?\n" +
	"\x04data\x18\x01 \x01(\v2).rpc.ListenResponse.EndpointResponse.DataH\x00R\x04data\x12\x16\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x1a\x90\x02\n" +
	"\x04Data\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x03R\x06status\x12U\n" +
	"\vhttp_method\x18\x02 \x01(\x0e24.rpc.ListenResponse.EndpointResponse.Data.HttpMethodR\n" +
	"httpMethod\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x19\n" +
	"\bevent_id\x18\x04 \x01(\tR\aeventId\"l\n" +
	"\n" +
	"HttpMethod\x12\x1b\n" +
	"\x17HTTP_METHOD_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fHTTP_METHOD_GET\x10\x01\x12\x14\n" +
	"\x10HTTP_METHOD_POST\x10\x02\x12\x16\n" +
	"\x12HTTP_METHOD_DELETE\x10\x03B\t\n" +
	"\acontent\"j\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_LOADING\x10\x01\x12\x16\n" +
	"\x12STATE_RECONNECTING\x10\x02\x12\x0f\n" +
	"\vSTATE_READY\x10\x03\x12\x0e\n" +
	"\n" +
	"STATE_DONE\x10\x04B\t\n" +
	"\acontentB\"Z github.com/stripe/stripe-cli/rpcb\x06proto3"

var (
	file_listen_proto_rawDescOnce sync.Once
	file_listen_proto_rawDescData []byte
)

func file_listen_proto_rawDescGZIP() []byte {
	file_listen_proto_rawDescOnce.Do(func() {
		file_listen_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_listen_proto_rawDesc), len(file_listen_proto_rawDesc)))
	})
	return file_listen_proto_rawDescData
}

var file_listen_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_listen_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_listen_proto_goTypes = []any{
	(ListenResponse_State)(0),                            // 0: rpc.ListenResponse.State
	(ListenResponse_EndpointResponse_Data_HttpMethod)(0), // 1: rpc.ListenResponse.EndpointResponse.Data.HttpMethod
	(*ListenRequest)(nil),                                // 2: rpc.ListenRequest
	(*ListenResponse)(nil),                               // 3: rpc.ListenResponse
	(*ListenResponse_EndpointResponse)(nil),              // 4: rpc.ListenResponse.EndpointResponse
	(*ListenResponse_EndpointResponse_Data)(nil),         // 5: rpc.ListenResponse.EndpointResponse.Data
	(*StripeEvent)(nil),                                  // 6: rpc.StripeEvent
	(*V2StripeEvent)(nil),                                // 7: rpc.V2StripeEvent
}
var file_listen_proto_depIdxs = []int32{
	0, // 0: rpc.ListenResponse.state:type_name -> rpc.ListenResponse.State
	6, // 1: rpc.ListenResponse.stripe_event:type_name -> rpc.StripeEvent
	4, // 2: rpc.ListenResponse.endpoint_response:type_name -> rpc.ListenResponse.EndpointResponse
	7, // 3: rpc.ListenResponse.v2_stripe_event:type_name -> rpc.V2StripeEvent
	5, // 4: rpc.ListenResponse.EndpointResponse.data:type_name -> rpc.ListenResponse.EndpointResponse.Data
	1, // 5: rpc.ListenResponse.EndpointResponse.Data.http_method:type_name -> rpc.ListenResponse.EndpointResponse.Data.HttpMethod
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_listen_proto_init() }
func file_listen_proto_init() {
	if File_listen_proto != nil {
		return
	}
	file_common_proto_init()
	file_listen_proto_msgTypes[1].OneofWrappers = []any{
		(*ListenResponse_State_)(nil),
		(*ListenResponse_StripeEvent)(nil),
		(*ListenResponse_EndpointResponse_)(nil),
		(*ListenResponse_V2StripeEvent)(nil),
	}
	file_listen_proto_msgTypes[2].OneofWrappers = []any{
		(*ListenResponse_EndpointResponse_Data_)(nil),
		(*ListenResponse_EndpointResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_listen_proto_rawDesc), len(file_listen_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_listen_proto_goTypes,
		DependencyIndexes: file_listen_proto_depIdxs,
		EnumInfos:         file_listen_proto_enumTypes,
		MessageInfos:      file_listen_proto_msgTypes,
	}.Build()
	File_listen_proto = out.File
	file_listen_proto_goTypes = nil
	file_listen_proto_depIdxs = nil
}
