// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: listen.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListenResponse_State int32

const (
	ListenResponse_STATE_UNSPECIFIED  ListenResponse_State = 0
	ListenResponse_STATE_LOADING      ListenResponse_State = 1
	ListenResponse_STATE_RECONNECTING ListenResponse_State = 2
	ListenResponse_STATE_READY        ListenResponse_State = 3
	ListenResponse_STATE_DONE         ListenResponse_State = 4
)

// Enum value maps for ListenResponse_State.
var (
	ListenResponse_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_LOADING",
		2: "STATE_RECONNECTING",
		3: "STATE_READY",
		4: "STATE_DONE",
	}
	ListenResponse_State_value = map[string]int32{
		"STATE_UNSPECIFIED":  0,
		"STATE_LOADING":      1,
		"STATE_RECONNECTING": 2,
		"STATE_READY":        3,
		"STATE_DONE":         4,
	}
)

func (x ListenResponse_State) Enum() *ListenResponse_State {
	p := new(ListenResponse_State)
	*p = x
	return p
}

func (x ListenResponse_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListenResponse_State) Descriptor() protoreflect.EnumDescriptor {
	return file_listen_proto_enumTypes[0].Descriptor()
}

func (ListenResponse_State) Type() protoreflect.EnumType {
	return &file_listen_proto_enumTypes[0]
}

func (x ListenResponse_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListenResponse_State.Descriptor instead.
func (ListenResponse_State) EnumDescriptor() ([]byte, []int) {
	return file_listen_proto_rawDescGZIP(), []int{1, 0}
}

type ListenResponse_EndpointResponse_Data_HttpMethod int32

const (
	ListenResponse_EndpointResponse_Data_HTTP_METHOD_UNSPECIFIED ListenResponse_EndpointResponse_Data_HttpMethod = 0
	ListenResponse_EndpointResponse_Data_HTTP_METHOD_GET         ListenResponse_EndpointResponse_Data_HttpMethod = 1
	ListenResponse_EndpointResponse_Data_HTTP_METHOD_POST        ListenResponse_EndpointResponse_Data_HttpMethod = 2
	ListenResponse_EndpointResponse_Data_HTTP_METHOD_DELETE      ListenResponse_EndpointResponse_Data_HttpMethod = 3
)

// Enum value maps for ListenResponse_EndpointResponse_Data_HttpMethod.
var (
	ListenResponse_EndpointResponse_Data_HttpMethod_name = map[int32]string{
		0: "HTTP_METHOD_UNSPECIFIED",
		1: "HTTP_METHOD_GET",
		2: "HTTP_METHOD_POST",
		3: "HTTP_METHOD_DELETE",
	}
	ListenResponse_EndpointResponse_Data_HttpMethod_value = map[string]int32{
		"HTTP_METHOD_UNSPECIFIED": 0,
		"HTTP_METHOD_GET":         1,
		"HTTP_METHOD_POST":        2,
		"HTTP_METHOD_DELETE":      3,
	}
)

func (x ListenResponse_EndpointResponse_Data_HttpMethod) Enum() *ListenResponse_EndpointResponse_Data_HttpMethod {
	p := new(ListenResponse_EndpointResponse_Data_HttpMethod)
	*p = x
	return p
}

func (x ListenResponse_EndpointResponse_Data_HttpMethod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListenResponse_EndpointResponse_Data_HttpMethod) Descriptor() protoreflect.EnumDescriptor {
	return file_listen_proto_enumTypes[1].Descriptor()
}

func (ListenResponse_EndpointResponse_Data_HttpMethod) Type() protoreflect.EnumType {
	return &file_listen_proto_enumTypes[1]
}

func (x ListenResponse_EndpointResponse_Data_HttpMethod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListenResponse_EndpointResponse_Data_HttpMethod.Descriptor instead.
func (ListenResponse_EndpointResponse_Data_HttpMethod) EnumDescriptor() ([]byte, []int) {
	return file_listen_proto_rawDescGZIP(), []int{1, 0, 0, 0}
}

type ListenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A list of custom headers to forward for Connect
	ConnectHeaders []string `protobuf:"bytes,1,rep,name=connect_headers,json=connectHeaders,proto3" json:"connect_headers,omitempty"`
	// A list of specific events to listen for. For a list of all possible events, see:
	// https://stripe.com/docs/api/events/types (default [*])
	Events []string `protobuf:"bytes,2,rep,name=events,proto3" json:"events,omitempty"`
	// The URL to forward Connect webhook events to (default: same as normal events)
	ForwardConnectTo string `protobuf:"bytes,3,opt,name=forward_connect_to,json=forwardConnectTo,proto3" json:"forward_connect_to,omitempty"`
	// The URL to forward webhook events to
	ForwardTo string `protobuf:"bytes,4,opt,name=forward_to,json=forwardTo,proto3" json:"forward_to,omitempty"`
	// A list of custom headers to forward
	Headers []string `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty"`
	// Receive events formatted with the latest API version (default: your account's default API
	// version)
	Latest bool `protobuf:"varint,6,opt,name=latest,proto3" json:"latest,omitempty"`
	// Receive live events (default: test)
	Live bool `protobuf:"varint,7,opt,name=live,proto3" json:"live,omitempty"`
	// Skip certificate verification when forwarding to HTTPS endpoints
	SkipVerify bool `protobuf:"varint,8,opt,name=skip_verify,json=skipVerify,proto3" json:"skip_verify,omitempty"`
	// Load webhook endpoint configuration from the webhooks API/dashboard
	UseConfiguredWebhooks bool `protobuf:"varint,9,opt,name=use_configured_webhooks,json=useConfiguredWebhooks,proto3" json:"use_configured_webhooks,omitempty"`
}

func (x *ListenRequest) Reset() {
	*x = ListenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listen_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenRequest) ProtoMessage() {}

func (x *ListenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_listen_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenRequest.ProtoReflect.Descriptor instead.
func (*ListenRequest) Descriptor() ([]byte, []int) {
	return file_listen_proto_rawDescGZIP(), []int{0}
}

func (x *ListenRequest) GetConnectHeaders() []string {
	if x != nil {
		return x.ConnectHeaders
	}
	return nil
}

func (x *ListenRequest) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *ListenRequest) GetForwardConnectTo() string {
	if x != nil {
		return x.ForwardConnectTo
	}
	return ""
}

func (x *ListenRequest) GetForwardTo() string {
	if x != nil {
		return x.ForwardTo
	}
	return ""
}

func (x *ListenRequest) GetHeaders() []string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *ListenRequest) GetLatest() bool {
	if x != nil {
		return x.Latest
	}
	return false
}

func (x *ListenRequest) GetLive() bool {
	if x != nil {
		return x.Live
	}
	return false
}

func (x *ListenRequest) GetSkipVerify() bool {
	if x != nil {
		return x.SkipVerify
	}
	return false
}

func (x *ListenRequest) GetUseConfiguredWebhooks() bool {
	if x != nil {
		return x.UseConfiguredWebhooks
	}
	return false
}

type ListenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//	*ListenResponse_State_
	//	*ListenResponse_StripeEvent
	//	*ListenResponse_EndpointResponse_
	Content isListenResponse_Content `protobuf_oneof:"content"`
}

func (x *ListenResponse) Reset() {
	*x = ListenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listen_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenResponse) ProtoMessage() {}

func (x *ListenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listen_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenResponse.ProtoReflect.Descriptor instead.
func (*ListenResponse) Descriptor() ([]byte, []int) {
	return file_listen_proto_rawDescGZIP(), []int{1}
}

func (m *ListenResponse) GetContent() isListenResponse_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *ListenResponse) GetState() ListenResponse_State {
	if x, ok := x.GetContent().(*ListenResponse_State_); ok {
		return x.State
	}
	return ListenResponse_STATE_UNSPECIFIED
}

func (x *ListenResponse) GetStripeEvent() *StripeEvent {
	if x, ok := x.GetContent().(*ListenResponse_StripeEvent); ok {
		return x.StripeEvent
	}
	return nil
}

func (x *ListenResponse) GetEndpointResponse() *ListenResponse_EndpointResponse {
	if x, ok := x.GetContent().(*ListenResponse_EndpointResponse_); ok {
		return x.EndpointResponse
	}
	return nil
}

type isListenResponse_Content interface {
	isListenResponse_Content()
}

type ListenResponse_State_ struct {
	// Check if the stream ready
	State ListenResponse_State `protobuf:"varint,1,opt,name=state,proto3,enum=rpc.ListenResponse_State,oneof"`
}

type ListenResponse_StripeEvent struct {
	// A Stripe event
	StripeEvent *StripeEvent `protobuf:"bytes,2,opt,name=stripe_event,json=stripeEvent,proto3,oneof"`
}

type ListenResponse_EndpointResponse_ struct {
	// A response from an endpoint
	EndpointResponse *ListenResponse_EndpointResponse `protobuf:"bytes,3,opt,name=endpoint_response,json=endpointResponse,proto3,oneof"`
}

func (*ListenResponse_State_) isListenResponse_Content() {}

func (*ListenResponse_StripeEvent) isListenResponse_Content() {}

func (*ListenResponse_EndpointResponse_) isListenResponse_Content() {}

type ListenResponse_EndpointResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Content:
	//	*ListenResponse_EndpointResponse_Data_
	//	*ListenResponse_EndpointResponse_Error
	Content isListenResponse_EndpointResponse_Content `protobuf_oneof:"content"`
}

func (x *ListenResponse_EndpointResponse) Reset() {
	*x = ListenResponse_EndpointResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listen_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListenResponse_EndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenResponse_EndpointResponse) ProtoMessage() {}

func (x *ListenResponse_EndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_listen_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenResponse_EndpointResponse.ProtoReflect.Descriptor instead.
func (*ListenResponse_EndpointResponse) Descriptor() ([]byte, []int) {
	return file_listen_proto_rawDescGZIP(), []int{1, 0}
}

func (m *ListenResponse_EndpointResponse) GetContent() isListenResponse_EndpointResponse_Content {
	if m != nil {
		return m.Content
	}
	return nil
}

func (x *ListenResponse_EndpointResponse) GetData() *ListenResponse_EndpointResponse_Data {
	if x, ok := x.GetContent().(*ListenResponse_EndpointResponse_Data_); ok {
		return x.Data
	}
	return nil
}

func (x *ListenResponse_EndpointResponse) GetError() string {
	if x, ok := x.GetContent().(*ListenResponse_EndpointResponse_Error); ok {
		return x.Error
	}
	return ""
}

type isListenResponse_EndpointResponse_Content interface {
	isListenResponse_EndpointResponse_Content()
}

type ListenResponse_EndpointResponse_Data_ struct {
	Data *ListenResponse_EndpointResponse_Data `protobuf:"bytes,1,opt,name=data,proto3,oneof"`
}

type ListenResponse_EndpointResponse_Error struct {
	Error string `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ListenResponse_EndpointResponse_Data_) isListenResponse_EndpointResponse_Content() {}

func (*ListenResponse_EndpointResponse_Error) isListenResponse_EndpointResponse_Content() {}

type ListenResponse_EndpointResponse_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// HTTP status code
	Status int64 `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	// HTTP method
	HttpMethod ListenResponse_EndpointResponse_Data_HttpMethod `protobuf:"varint,2,opt,name=http_method,json=httpMethod,proto3,enum=rpc.ListenResponse_EndpointResponse_Data_HttpMethod" json:"http_method,omitempty"`
	// URL of the webhook endpoint
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// ID of the Stripe event that caused this response
	EventId string `protobuf:"bytes,4,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
}

func (x *ListenResponse_EndpointResponse_Data) Reset() {
	*x = ListenResponse_EndpointResponse_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_listen_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListenResponse_EndpointResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListenResponse_EndpointResponse_Data) ProtoMessage() {}

func (x *ListenResponse_EndpointResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_listen_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListenResponse_EndpointResponse_Data.ProtoReflect.Descriptor instead.
func (*ListenResponse_EndpointResponse_Data) Descriptor() ([]byte, []int) {
	return file_listen_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *ListenResponse_EndpointResponse_Data) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListenResponse_EndpointResponse_Data) GetHttpMethod() ListenResponse_EndpointResponse_Data_HttpMethod {
	if x != nil {
		return x.HttpMethod
	}
	return ListenResponse_EndpointResponse_Data_HTTP_METHOD_UNSPECIFIED
}

func (x *ListenResponse_EndpointResponse_Data) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *ListenResponse_EndpointResponse_Data) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

var File_listen_proto protoreflect.FileDescriptor

var file_listen_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x72, 0x70, 0x63, 0x1a, 0x0c, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0xbc, 0x02, 0x0a, 0x0d, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x27, 0x0a, 0x0f, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x5f, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x63, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x5f,
	0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x5f, 0x74, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x54, 0x6f, 0x12, 0x1d, 0x0a, 0x0a, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x5f, 0x74, 0x6f,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x54,
	0x6f, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c,
	0x61, 0x74, 0x65, 0x73, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x6c, 0x61, 0x74,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6c, 0x69, 0x76, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x04, 0x6c, 0x69, 0x76, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x6b, 0x69, 0x70, 0x5f,
	0x76, 0x65, 0x72, 0x69, 0x66, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x73, 0x6b,
	0x69, 0x70, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x12, 0x36, 0x0a, 0x17, 0x75, 0x73, 0x65, 0x5f,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x5f, 0x77, 0x65, 0x62, 0x68, 0x6f,
	0x6f, 0x6b, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x75, 0x73, 0x65, 0x43, 0x6f,
	0x6e, 0x66, 0x69, 0x67, 0x75, 0x72, 0x65, 0x64, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x73,
	0x22, 0xd2, 0x05, 0x0a, 0x0e, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x19, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52,
	0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x35, 0x0a, 0x0c, 0x73, 0x74, 0x72, 0x69, 0x70, 0x65,
	0x5f, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x53, 0x74, 0x72, 0x69, 0x70, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x48, 0x00,
	0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x70, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x53, 0x0a,
	0x11, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4c,
	0x69, 0x73, 0x74, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x48, 0x00,
	0x52, 0x10, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x1a, 0x89, 0x03, 0x0a, 0x10, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73, 0x74,
	0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x6e, 0x64, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74, 0x61,
	0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x1a, 0x90, 0x02, 0x0a, 0x04, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x55, 0x0a, 0x0b, 0x68, 0x74, 0x74, 0x70, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x34, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x4c, 0x69, 0x73,
	0x74, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x45, 0x6e, 0x64, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x61, 0x74,
	0x61, 0x2e, 0x48, 0x74, 0x74, 0x70, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x52, 0x0a, 0x68, 0x74,
	0x74, 0x70, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x6c, 0x0a, 0x0a, 0x48, 0x74, 0x74, 0x70, 0x4d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x12, 0x1b, 0x0a, 0x17, 0x48, 0x54, 0x54, 0x50, 0x5f, 0x4d, 0x45, 0x54, 0x48,
	0x4f, 0x44, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00,
	0x12, 0x13, 0x0a, 0x0f, 0x48, 0x54, 0x54, 0x50, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f,
	0x47, 0x45, 0x54, 0x10, 0x01, 0x12, 0x14, 0x0a, 0x10, 0x48, 0x54, 0x54, 0x50, 0x5f, 0x4d, 0x45,
	0x54, 0x48, 0x4f, 0x44, 0x5f, 0x50, 0x4f, 0x53, 0x54, 0x10, 0x02, 0x12, 0x16, 0x0a, 0x12, 0x48,
	0x54, 0x54, 0x50, 0x5f, 0x4d, 0x45, 0x54, 0x48, 0x4f, 0x44, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54,
	0x45, 0x10, 0x03, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x6a,
	0x0a, 0x05, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x15, 0x0a, 0x11, 0x53, 0x54, 0x41, 0x54, 0x45,
	0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x11,
	0x0a, 0x0d, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x4c, 0x4f, 0x41, 0x44, 0x49, 0x4e, 0x47, 0x10,
	0x01, 0x12, 0x16, 0x0a, 0x12, 0x53, 0x54, 0x41, 0x54, 0x45, 0x5f, 0x52, 0x45, 0x43, 0x4f, 0x4e,
	0x4e, 0x45, 0x43, 0x54, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0f, 0x0a, 0x0b, 0x53, 0x54, 0x41,
	0x54, 0x45, 0x5f, 0x52, 0x45, 0x41, 0x44, 0x59, 0x10, 0x03, 0x12, 0x0e, 0x0a, 0x0a, 0x53, 0x54,
	0x41, 0x54, 0x45, 0x5f, 0x44, 0x4f, 0x4e, 0x45, 0x10, 0x04, 0x42, 0x09, 0x0a, 0x07, 0x63, 0x6f,
	0x6e, 0x74, 0x65, 0x6e, 0x74, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x73, 0x74, 0x72, 0x69, 0x70, 0x65, 0x2f, 0x73, 0x74, 0x72, 0x69, 0x70,
	0x65, 0x2d, 0x63, 0x6c, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_listen_proto_rawDescOnce sync.Once
	file_listen_proto_rawDescData = file_listen_proto_rawDesc
)

func file_listen_proto_rawDescGZIP() []byte {
	file_listen_proto_rawDescOnce.Do(func() {
		file_listen_proto_rawDescData = protoimpl.X.CompressGZIP(file_listen_proto_rawDescData)
	})
	return file_listen_proto_rawDescData
}

var file_listen_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_listen_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_listen_proto_goTypes = []interface{}{
	(ListenResponse_State)(0),                            // 0: rpc.ListenResponse.State
	(ListenResponse_EndpointResponse_Data_HttpMethod)(0), // 1: rpc.ListenResponse.EndpointResponse.Data.HttpMethod
	(*ListenRequest)(nil),                                // 2: rpc.ListenRequest
	(*ListenResponse)(nil),                               // 3: rpc.ListenResponse
	(*ListenResponse_EndpointResponse)(nil),              // 4: rpc.ListenResponse.EndpointResponse
	(*ListenResponse_EndpointResponse_Data)(nil),         // 5: rpc.ListenResponse.EndpointResponse.Data
	(*StripeEvent)(nil),                                  // 6: rpc.StripeEvent
}
var file_listen_proto_depIdxs = []int32{
	0, // 0: rpc.ListenResponse.state:type_name -> rpc.ListenResponse.State
	6, // 1: rpc.ListenResponse.stripe_event:type_name -> rpc.StripeEvent
	4, // 2: rpc.ListenResponse.endpoint_response:type_name -> rpc.ListenResponse.EndpointResponse
	5, // 3: rpc.ListenResponse.EndpointResponse.data:type_name -> rpc.ListenResponse.EndpointResponse.Data
	1, // 4: rpc.ListenResponse.EndpointResponse.Data.http_method:type_name -> rpc.ListenResponse.EndpointResponse.Data.HttpMethod
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_listen_proto_init() }
func file_listen_proto_init() {
	if File_listen_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_listen_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listen_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listen_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListenResponse_EndpointResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_listen_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListenResponse_EndpointResponse_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_listen_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ListenResponse_State_)(nil),
		(*ListenResponse_StripeEvent)(nil),
		(*ListenResponse_EndpointResponse_)(nil),
	}
	file_listen_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*ListenResponse_EndpointResponse_Data_)(nil),
		(*ListenResponse_EndpointResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_listen_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_listen_proto_goTypes,
		DependencyIndexes: file_listen_proto_depIdxs,
		EnumInfos:         file_listen_proto_enumTypes,
		MessageInfos:      file_listen_proto_msgTypes,
	}.Build()
	File_listen_proto = out.File
	file_listen_proto_rawDesc = nil
	file_listen_proto_goTypes = nil
	file_listen_proto_depIdxs = nil
}
