// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: login_status.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginStatusRequest) Reset() {
	*x = LoginStatusRequest{}
	mi := &file_login_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginStatusRequest) ProtoMessage() {}

func (x *LoginStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_login_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginStatusRequest.ProtoReflect.Descriptor instead.
func (*LoginStatusRequest) Descriptor() ([]byte, []int) {
	return file_login_status_proto_rawDescGZIP(), []int{0}
}

type LoginStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the Stripe account, e.g. acct_123
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Display name of the Stripe account
	DisplayName   string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginStatusResponse) Reset() {
	*x = LoginStatusResponse{}
	mi := &file_login_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginStatusResponse) ProtoMessage() {}

func (x *LoginStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_login_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginStatusResponse.ProtoReflect.Descriptor instead.
func (*LoginStatusResponse) Descriptor() ([]byte, []int) {
	return file_login_status_proto_rawDescGZIP(), []int{1}
}

func (x *LoginStatusResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *LoginStatusResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

var File_login_status_proto protoreflect.FileDescriptor

const file_login_status_proto_rawDesc = "" +
	"\n" +
	"\x12login_status.proto\x12\x03rpc\"\x14\n" +
	"\x12LoginStatusRequest\"W\n" +
	"\x13LoginStatusResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayNameB\"Z github.com/stripe/stripe-cli/rpcb\x06proto3"

var (
	file_login_status_proto_rawDescOnce sync.Once
	file_login_status_proto_rawDescData []byte
)

func file_login_status_proto_rawDescGZIP() []byte {
	file_login_status_proto_rawDescOnce.Do(func() {
		file_login_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_login_status_proto_rawDesc), len(file_login_status_proto_rawDesc)))
	})
	return file_login_status_proto_rawDescData
}

var file_login_status_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_login_status_proto_goTypes = []any{
	(*LoginStatusRequest)(nil),  // 0: rpc.LoginStatusRequest
	(*LoginStatusResponse)(nil), // 1: rpc.LoginStatusResponse
}
var file_login_status_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_login_status_proto_init() }
func file_login_status_proto_init() {
	if File_login_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_login_status_proto_rawDesc), len(file_login_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_login_status_proto_goTypes,
		DependencyIndexes: file_login_status_proto_depIdxs,
		MessageInfos:      file_login_status_proto_msgTypes,
	}.Build()
	File_login_status_proto = out.File
	file_login_status_proto_goTypes = nil
	file_login_status_proto_depIdxs = nil
}
