// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: samples_list.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SamplesListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SamplesListRequest) Reset() {
	*x = SamplesListRequest{}
	mi := &file_samples_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplesListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplesListRequest) ProtoMessage() {}

func (x *SamplesListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_samples_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplesListRequest.ProtoReflect.Descriptor instead.
func (*SamplesListRequest) Descriptor() ([]byte, []int) {
	return file_samples_list_proto_rawDescGZIP(), []int{0}
}

type SamplesListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of available Stripe samples
	Samples       []*SamplesListResponse_SampleData `protobuf:"bytes,1,rep,name=samples,proto3" json:"samples,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SamplesListResponse) Reset() {
	*x = SamplesListResponse{}
	mi := &file_samples_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplesListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplesListResponse) ProtoMessage() {}

func (x *SamplesListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_samples_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplesListResponse.ProtoReflect.Descriptor instead.
func (*SamplesListResponse) Descriptor() ([]byte, []int) {
	return file_samples_list_proto_rawDescGZIP(), []int{1}
}

func (x *SamplesListResponse) GetSamples() []*SamplesListResponse_SampleData {
	if x != nil {
		return x.Samples
	}
	return nil
}

type SamplesListResponse_SampleData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the sample, e.g. accept-a-card-payment
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// URL of the repo, e.g. https://github.com/stripe-samples/accept-a-card-payment
	Url string `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	// Description of the sample, e.g. Learn how to accept a basic card payment
	Description   string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SamplesListResponse_SampleData) Reset() {
	*x = SamplesListResponse_SampleData{}
	mi := &file_samples_list_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SamplesListResponse_SampleData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SamplesListResponse_SampleData) ProtoMessage() {}

func (x *SamplesListResponse_SampleData) ProtoReflect() protoreflect.Message {
	mi := &file_samples_list_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SamplesListResponse_SampleData.ProtoReflect.Descriptor instead.
func (*SamplesListResponse_SampleData) Descriptor() ([]byte, []int) {
	return file_samples_list_proto_rawDescGZIP(), []int{1, 0}
}

func (x *SamplesListResponse_SampleData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SamplesListResponse_SampleData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *SamplesListResponse_SampleData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

var File_samples_list_proto protoreflect.FileDescriptor

const file_samples_list_proto_rawDesc = "" +
	"\n" +
	"\x12samples_list.proto\x12\x03rpc\"\x14\n" +
	"\x12SamplesListRequest\"\xaa\x01\n" +
	"\x13SamplesListResponse\x12=\n" +
	"\asamples\x18\x01 \x03(\v2#.rpc.SamplesListResponse.SampleDataR\asamples\x1aT\n" +
	"\n" +
	"SampleData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescriptionB\"Z github.com/stripe/stripe-cli/rpcb\x06proto3"

var (
	file_samples_list_proto_rawDescOnce sync.Once
	file_samples_list_proto_rawDescData []byte
)

func file_samples_list_proto_rawDescGZIP() []byte {
	file_samples_list_proto_rawDescOnce.Do(func() {
		file_samples_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_samples_list_proto_rawDesc), len(file_samples_list_proto_rawDesc)))
	})
	return file_samples_list_proto_rawDescData
}

var file_samples_list_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_samples_list_proto_goTypes = []any{
	(*SamplesListRequest)(nil),             // 0: rpc.SamplesListRequest
	(*SamplesListResponse)(nil),            // 1: rpc.SamplesListResponse
	(*SamplesListResponse_SampleData)(nil), // 2: rpc.SamplesListResponse.SampleData
}
var file_samples_list_proto_depIdxs = []int32{
	2, // 0: rpc.SamplesListResponse.samples:type_name -> rpc.SamplesListResponse.SampleData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_samples_list_proto_init() }
func file_samples_list_proto_init() {
	if File_samples_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_samples_list_proto_rawDesc), len(file_samples_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_samples_list_proto_goTypes,
		DependencyIndexes: file_samples_list_proto_depIdxs,
		MessageInfos:      file_samples_list_proto_msgTypes,
	}.Build()
	File_samples_list_proto = out.File
	file_samples_list_proto_goTypes = nil
	file_samples_list_proto_depIdxs = nil
}
