// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: switch_context.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SwitchContextRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ID of the Stripe account to switch to, e.g. acct_123. Required: unlike
	// `stripe switch context`, this RPC has no interactive picker to fall back on.
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Switch to live mode for the given account. Defaults to test mode (sandbox).
	Live          bool `protobuf:"varint,2,opt,name=live,proto3" json:"live,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchContextRequest) Reset() {
	*x = SwitchContextRequest{}
	mi := &file_switch_context_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchContextRequest) ProtoMessage() {}

func (x *SwitchContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_switch_context_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchContextRequest.ProtoReflect.Descriptor instead.
func (*SwitchContextRequest) Descriptor() ([]byte, []int) {
	return file_switch_context_proto_rawDescGZIP(), []int{0}
}

func (x *SwitchContextRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SwitchContextRequest) GetLive() bool {
	if x != nil {
		return x.Live
	}
	return false
}

type SwitchContextResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of the now-active Stripe account, e.g. acct_123
	AccountId string `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	// Display name of the now-active Stripe account
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Whether the active context is now in live mode
	Live          bool `protobuf:"varint,3,opt,name=live,proto3" json:"live,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchContextResponse) Reset() {
	*x = SwitchContextResponse{}
	mi := &file_switch_context_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchContextResponse) ProtoMessage() {}

func (x *SwitchContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_switch_context_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchContextResponse.ProtoReflect.Descriptor instead.
func (*SwitchContextResponse) Descriptor() ([]byte, []int) {
	return file_switch_context_proto_rawDescGZIP(), []int{1}
}

func (x *SwitchContextResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SwitchContextResponse) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *SwitchContextResponse) GetLive() bool {
	if x != nil {
		return x.Live
	}
	return false
}

var File_switch_context_proto protoreflect.FileDescriptor

const file_switch_context_proto_rawDesc = "" +
	"\n" +
	"\x14switch_context.proto\x12\x03rpc\"I\n" +
	"\x14SwitchContextRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x12\n" +
	"\x04live\x18\x02 \x01(\bR\x04live\"m\n" +
	"\x15SwitchContextResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12\x12\n" +
	"\x04live\x18\x03 \x01(\bR\x04liveB\"Z github.com/stripe/stripe-cli/rpcb\x06proto3"

var (
	file_switch_context_proto_rawDescOnce sync.Once
	file_switch_context_proto_rawDescData []byte
)

func file_switch_context_proto_rawDescGZIP() []byte {
	file_switch_context_proto_rawDescOnce.Do(func() {
		file_switch_context_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_switch_context_proto_rawDesc), len(file_switch_context_proto_rawDesc)))
	})
	return file_switch_context_proto_rawDescData
}

var file_switch_context_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_switch_context_proto_goTypes = []any{
	(*SwitchContextRequest)(nil),  // 0: rpc.SwitchContextRequest
	(*SwitchContextResponse)(nil), // 1: rpc.SwitchContextResponse
}
var file_switch_context_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_switch_context_proto_init() }
func file_switch_context_proto_init() {
	if File_switch_context_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_switch_context_proto_rawDesc), len(file_switch_context_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_switch_context_proto_goTypes,
		DependencyIndexes: file_switch_context_proto_depIdxs,
		MessageInfos:      file_switch_context_proto_msgTypes,
	}.Build()
	File_switch_context_proto = out.File
	file_switch_context_proto_goTypes = nil
	file_switch_context_proto_depIdxs = nil
}
