// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: triggers_list.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TriggersListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggersListRequest) Reset() {
	*x = TriggersListRequest{}
	mi := &file_triggers_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggersListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggersListRequest) ProtoMessage() {}

func (x *TriggersListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_triggers_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggersListRequest.ProtoReflect.Descriptor instead.
func (*TriggersListRequest) Descriptor() ([]byte, []int) {
	return file_triggers_list_proto_rawDescGZIP(), []int{0}
}

type TriggersListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list of supported events for `Trigger`.
	Events        []string `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggersListResponse) Reset() {
	*x = TriggersListResponse{}
	mi := &file_triggers_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggersListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggersListResponse) ProtoMessage() {}

func (x *TriggersListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_triggers_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggersListResponse.ProtoReflect.Descriptor instead.
func (*TriggersListResponse) Descriptor() ([]byte, []int) {
	return file_triggers_list_proto_rawDescGZIP(), []int{1}
}

func (x *TriggersListResponse) GetEvents() []string {
	if x != nil {
		return x.Events
	}
	return nil
}

var File_triggers_list_proto protoreflect.FileDescriptor

const file_triggers_list_proto_rawDesc = "" +
	"\n" +
	"\x13triggers_list.proto\x12\x03rpc\"\x15\n" +
	"\x13TriggersListRequest\".\n" +
	"\x14TriggersListResponse\x12\x16\n" +
	"\x06events\x18\x01 \x03(\tR\x06eventsB\"Z github.com/stripe/stripe-cli/rpcb\x06proto3"

var (
	file_triggers_list_proto_rawDescOnce sync.Once
	file_triggers_list_proto_rawDescData []byte
)

func file_triggers_list_proto_rawDescGZIP() []byte {
	file_triggers_list_proto_rawDescOnce.Do(func() {
		file_triggers_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_triggers_list_proto_rawDesc), len(file_triggers_list_proto_rawDesc)))
	})
	return file_triggers_list_proto_rawDescData
}

var file_triggers_list_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_triggers_list_proto_goTypes = []any{
	(*TriggersListRequest)(nil),  // 0: rpc.TriggersListRequest
	(*TriggersListResponse)(nil), // 1: rpc.TriggersListResponse
}
var file_triggers_list_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_triggers_list_proto_init() }
func file_triggers_list_proto_init() {
	if File_triggers_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_triggers_list_proto_rawDesc), len(file_triggers_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_triggers_list_proto_goTypes,
		DependencyIndexes: file_triggers_list_proto_depIdxs,
		MessageInfos:      file_triggers_list_proto_msgTypes,
	}.Build()
	File_triggers_list_proto = out.File
	file_triggers_list_proto_goTypes = nil
	file_triggers_list_proto_depIdxs = nil
}
