// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: trigger.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TriggerRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An event to trigger. Use `TriggersList` to see the available events.
	Event string `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	// Set a header identifying the connected account
	StripeAccount string `protobuf:"bytes,2,opt,name=stripe_account,json=stripeAccount,proto3" json:"stripe_account,omitempty"`
	// Skip specific steps in the fixture
	Skip []string `protobuf:"bytes,3,rep,name=skip,proto3" json:"skip,omitempty"`
	// Override parameters in the fixture
	Override []string `protobuf:"bytes,4,rep,name=override,proto3" json:"override,omitempty"`
	// Add parameters in the fixture
	Add []string `protobuf:"bytes,5,rep,name=add,proto3" json:"add,omitempty"`
	// Remove parameters from the fixture
	Remove []string `protobuf:"bytes,6,rep,name=remove,proto3" json:"remove,omitempty"`
	// Raw fixture string
	Raw string `protobuf:"bytes,7,opt,name=raw,proto3" json:"raw,omitempty"`
	// Specify API Version for fixture
	ApiVersion string `protobuf:"bytes,8,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	// Whether or not to edit the fixture directly in git's default IDE
	Edit          bool `protobuf:"varint,9,opt,name=edit,proto3" json:"edit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRequest) Reset() {
	*x = TriggerRequest{}
	mi := &file_trigger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRequest) ProtoMessage() {}

func (x *TriggerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRequest.ProtoReflect.Descriptor instead.
func (*TriggerRequest) Descriptor() ([]byte, []int) {
	return file_trigger_proto_rawDescGZIP(), []int{0}
}

func (x *TriggerRequest) GetEvent() string {
	if x != nil {
		return x.Event
	}
	return ""
}

func (x *TriggerRequest) GetStripeAccount() string {
	if x != nil {
		return x.StripeAccount
	}
	return ""
}

func (x *TriggerRequest) GetSkip() []string {
	if x != nil {
		return x.Skip
	}
	return nil
}

func (x *TriggerRequest) GetOverride() []string {
	if x != nil {
		return x.Override
	}
	return nil
}

func (x *TriggerRequest) GetAdd() []string {
	if x != nil {
		return x.Add
	}
	return nil
}

func (x *TriggerRequest) GetRemove() []string {
	if x != nil {
		return x.Remove
	}
	return nil
}

func (x *TriggerRequest) GetRaw() string {
	if x != nil {
		return x.Raw
	}
	return ""
}

func (x *TriggerRequest) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *TriggerRequest) GetEdit() bool {
	if x != nil {
		return x.Edit
	}
	return false
}

type TriggerResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of requests made during this trigger
	Requests      []string `protobuf:"bytes,1,rep,name=requests,proto3" json:"requests,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerResponse) Reset() {
	*x = TriggerResponse{}
	mi := &file_trigger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerResponse) ProtoMessage() {}

func (x *TriggerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_trigger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerResponse.ProtoReflect.Descriptor instead.
func (*TriggerResponse) Descriptor() ([]byte, []int) {
	return file_trigger_proto_rawDescGZIP(), []int{1}
}

func (x *TriggerResponse) GetRequests() []string {
	if x != nil {
		return x.Requests
	}
	return nil
}

var File_trigger_proto protoreflect.FileDescriptor

const file_trigger_proto_rawDesc = "" +
	"\n" +
	"\rtrigger.proto\x12\x03rpc\"\xee\x01\n" +
	"\x0eTriggerRequest\x12\x14\n" +
	"\x05event\x18\x01 \x01(\tR\x05event\x12%\n" +
	"\x0estripe_account\x18\x02 \x01(\tR\rstripeAccount\x12\x12\n" +
	"\x04skip\x18\x03 \x03(\tR\x04skip\x12\x1a\n" +
	"\boverride\x18\x04 \x03(\tR\boverride\x12\x10\n" +
	"\x03add\x18\x05 \x03(\tR\x03add\x12\x16\n" +
	"\x06remove\x18\x06 \x03(\tR\x06remove\x12\x10\n" +
	"\x03raw\x18\a \x01(\tR\x03raw\x12\x1f\n" +
	"\vapi_version\x18\b \x01(\tR\n" +
	"apiVersion\x12\x12\n" +
	"\x04edit\x18\t \x01(\bR\x04edit\"-\n" +
	"\x0fTriggerResponse\x12\x1a\n" +
	"\brequests\x18\x01 \x03(\tR\brequestsB\"Z github.com/stripe/stripe-cli/rpcb\x06proto3"

var (
	file_trigger_proto_rawDescOnce sync.Once
	file_trigger_proto_rawDescData []byte
)

func file_trigger_proto_rawDescGZIP() []byte {
	file_trigger_proto_rawDescOnce.Do(func() {
		file_trigger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trigger_proto_rawDesc), len(file_trigger_proto_rawDesc)))
	})
	return file_trigger_proto_rawDescData
}

var file_trigger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_trigger_proto_goTypes = []any{
	(*TriggerRequest)(nil),  // 0: rpc.TriggerRequest
	(*TriggerResponse)(nil), // 1: rpc.TriggerResponse
}
var file_trigger_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trigger_proto_init() }
func file_trigger_proto_init() {
	if File_trigger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trigger_proto_rawDesc), len(file_trigger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trigger_proto_goTypes,
		DependencyIndexes: file_trigger_proto_depIdxs,
		MessageInfos:      file_trigger_proto_msgTypes,
	}.Build()
	File_trigger_proto = out.File
	file_trigger_proto_goTypes = nil
	file_trigger_proto_depIdxs = nil
}
