// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: webhook_endpoints_list.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebhookEndpointsListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookEndpointsListRequest) Reset() {
	*x = WebhookEndpointsListRequest{}
	mi := &file_webhook_endpoints_list_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookEndpointsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEndpointsListRequest) ProtoMessage() {}

func (x *WebhookEndpointsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_endpoints_list_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEndpointsListRequest.ProtoReflect.Descriptor instead.
func (*WebhookEndpointsListRequest) Descriptor() ([]byte, []int) {
	return file_webhook_endpoints_list_proto_rawDescGZIP(), []int{0}
}

type WebhookEndpointsListResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// A list webhook endpoints
	Endpoints     []*WebhookEndpointsListResponse_WebhookEndpointData `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookEndpointsListResponse) Reset() {
	*x = WebhookEndpointsListResponse{}
	mi := &file_webhook_endpoints_list_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookEndpointsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEndpointsListResponse) ProtoMessage() {}

func (x *WebhookEndpointsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_endpoints_list_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEndpointsListResponse.ProtoReflect.Descriptor instead.
func (*WebhookEndpointsListResponse) Descriptor() ([]byte, []int) {
	return file_webhook_endpoints_list_proto_rawDescGZIP(), []int{1}
}

func (x *WebhookEndpointsListResponse) GetEndpoints() []*WebhookEndpointsListResponse_WebhookEndpointData {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type WebhookEndpointsListResponse_WebhookEndpointData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Webhook endpoint application
	Application string `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	// Enabled events of the webhook endpoint
	EnabledEvents []string `protobuf:"bytes,2,rep,name=enabledEvents,proto3" json:"enabledEvents,omitempty"`
	// Webhook endpoint URL
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// Webhook endpoint status
	Status        string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookEndpointsListResponse_WebhookEndpointData) Reset() {
	*x = WebhookEndpointsListResponse_WebhookEndpointData{}
	mi := &file_webhook_endpoints_list_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookEndpointsListResponse_WebhookEndpointData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEndpointsListResponse_WebhookEndpointData) ProtoMessage() {}

func (x *WebhookEndpointsListResponse_WebhookEndpointData) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_endpoints_list_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEndpointsListResponse_WebhookEndpointData.ProtoReflect.Descriptor instead.
func (*WebhookEndpointsListResponse_WebhookEndpointData) Descriptor() ([]byte, []int) {
	return file_webhook_endpoints_list_proto_rawDescGZIP(), []int{1, 0}
}

func (x *WebhookEndpointsListResponse_WebhookEndpointData) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *WebhookEndpointsListResponse_WebhookEndpointData) GetEnabledEvents() []string {
	if x != nil {
		return x.EnabledEvents
	}
	return nil
}

func (x *WebhookEndpointsListResponse_WebhookEndpointData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebhookEndpointsListResponse_WebhookEndpointData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_webhook_endpoints_list_proto protoreflect.FileDescriptor

const file_webhook_endpoints_list_proto_rawDesc = "" +
	"\n" +
	"\x1cwebhook_endpoints_list.proto\x12\x03rpc\"\x1d\n" +
	"\x1bWebhookEndpointsListRequest\"\xfd\x01\n" +
	"\x1cWebhookEndpointsListResponse\x12S\n" +
	"\tendpoints\x18\x01 \x03(\v25.rpc.WebhookEndpointsListResponse.WebhookEndpointDataR\tendpoints\x1a\x87\x01\n" +
	"\x13WebhookEndpointData\x12 \n" +
	"\vapplication\x18\x01 \x01(\tR\vapplication\x12$\n" +
	"\renabledEvents\x18\x02 \x03(\tR\renabledEvents\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06statusB\"Z github.com/stripe/stripe-cli/rpcb\x06proto3"

var (
	file_webhook_endpoints_list_proto_rawDescOnce sync.Once
	file_webhook_endpoints_list_proto_rawDescData []byte
)

func file_webhook_endpoints_list_proto_rawDescGZIP() []byte {
	file_webhook_endpoints_list_proto_rawDescOnce.Do(func() {
		file_webhook_endpoints_list_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_webhook_endpoints_list_proto_rawDesc), len(file_webhook_endpoints_list_proto_rawDesc)))
	})
	return file_webhook_endpoints_list_proto_rawDescData
}

var file_webhook_endpoints_list_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_webhook_endpoints_list_proto_goTypes = []any{
	(*WebhookEndpointsListRequest)(nil),                      // 0: rpc.WebhookEndpointsListRequest
	(*WebhookEndpointsListResponse)(nil),                     // 1: rpc.WebhookEndpointsListResponse
	(*WebhookEndpointsListResponse_WebhookEndpointData)(nil), // 2: rpc.WebhookEndpointsListResponse.WebhookEndpointData
}
var file_webhook_endpoints_list_proto_depIdxs = []int32{
	2, // 0: rpc.WebhookEndpointsListResponse.endpoints:type_name -> rpc.WebhookEndpointsListResponse.WebhookEndpointData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_webhook_endpoints_list_proto_init() }
func file_webhook_endpoints_list_proto_init() {
	if File_webhook_endpoints_list_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_webhook_endpoints_list_proto_rawDesc), len(file_webhook_endpoints_list_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webhook_endpoints_list_proto_goTypes,
		DependencyIndexes: file_webhook_endpoints_list_proto_depIdxs,
		MessageInfos:      file_webhook_endpoints_list_proto_msgTypes,
	}.Build()
	File_webhook_endpoints_list_proto = out.File
	file_webhook_endpoints_list_proto_goTypes = nil
	file_webhook_endpoints_list_proto_depIdxs = nil
}
