// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: webhook_endpoints_list.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WebhookEndpointsListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *WebhookEndpointsListRequest) Reset() {
	*x = WebhookEndpointsListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webhook_endpoints_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebhookEndpointsListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEndpointsListRequest) ProtoMessage() {}

func (x *WebhookEndpointsListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_endpoints_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEndpointsListRequest.ProtoReflect.Descriptor instead.
func (*WebhookEndpointsListRequest) Descriptor() ([]byte, []int) {
	return file_webhook_endpoints_list_proto_rawDescGZIP(), []int{0}
}

type WebhookEndpointsListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A list webhook endpoints
	Endpoints []*WebhookEndpointsListResponse_WebhookEndpointData `protobuf:"bytes,1,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
}

func (x *WebhookEndpointsListResponse) Reset() {
	*x = WebhookEndpointsListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webhook_endpoints_list_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebhookEndpointsListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEndpointsListResponse) ProtoMessage() {}

func (x *WebhookEndpointsListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_endpoints_list_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEndpointsListResponse.ProtoReflect.Descriptor instead.
func (*WebhookEndpointsListResponse) Descriptor() ([]byte, []int) {
	return file_webhook_endpoints_list_proto_rawDescGZIP(), []int{1}
}

func (x *WebhookEndpointsListResponse) GetEndpoints() []*WebhookEndpointsListResponse_WebhookEndpointData {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type WebhookEndpointsListResponse_WebhookEndpointData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Webhook endpoint application
	Application string `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	// Enabled events of the webhook endpoint
	EnabledEvents []string `protobuf:"bytes,2,rep,name=enabledEvents,proto3" json:"enabledEvents,omitempty"`
	// Webhook endpoint URL
	Url string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	// Webhook endpoint status
	Status string `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *WebhookEndpointsListResponse_WebhookEndpointData) Reset() {
	*x = WebhookEndpointsListResponse_WebhookEndpointData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_webhook_endpoints_list_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WebhookEndpointsListResponse_WebhookEndpointData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookEndpointsListResponse_WebhookEndpointData) ProtoMessage() {}

func (x *WebhookEndpointsListResponse_WebhookEndpointData) ProtoReflect() protoreflect.Message {
	mi := &file_webhook_endpoints_list_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookEndpointsListResponse_WebhookEndpointData.ProtoReflect.Descriptor instead.
func (*WebhookEndpointsListResponse_WebhookEndpointData) Descriptor() ([]byte, []int) {
	return file_webhook_endpoints_list_proto_rawDescGZIP(), []int{1, 0}
}

func (x *WebhookEndpointsListResponse_WebhookEndpointData) GetApplication() string {
	if x != nil {
		return x.Application
	}
	return ""
}

func (x *WebhookEndpointsListResponse_WebhookEndpointData) GetEnabledEvents() []string {
	if x != nil {
		return x.EnabledEvents
	}
	return nil
}

func (x *WebhookEndpointsListResponse_WebhookEndpointData) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebhookEndpointsListResponse_WebhookEndpointData) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_webhook_endpoints_list_proto protoreflect.FileDescriptor

var file_webhook_endpoints_list_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x5f, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x72, 0x70, 0x63, 0x22, 0x1d, 0x0a, 0x1b, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0xfd, 0x01, 0x0a, 0x1c, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x6e,
	0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x09, 0x65, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x57, 0x65, 0x62,
	0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x4c, 0x69, 0x73,
	0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f,
	0x6b, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x09, 0x65,
	0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x1a, 0x87, 0x01, 0x0a, 0x13, 0x57, 0x65, 0x62,
	0x68, 0x6f, 0x6f, 0x6b, 0x45, 0x6e, 0x64, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61,
	0x12, 0x20, 0x0a, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x63, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0d, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x65, 0x6e, 0x61, 0x62, 0x6c,
	0x65, 0x64, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x42, 0x22, 0x5a, 0x20, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x74, 0x72, 0x69, 0x70, 0x65, 0x2f, 0x73, 0x74, 0x72, 0x69, 0x70, 0x65, 0x2d, 0x63,
	0x6c, 0x69, 0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_webhook_endpoints_list_proto_rawDescOnce sync.Once
	file_webhook_endpoints_list_proto_rawDescData = file_webhook_endpoints_list_proto_rawDesc
)

func file_webhook_endpoints_list_proto_rawDescGZIP() []byte {
	file_webhook_endpoints_list_proto_rawDescOnce.Do(func() {
		file_webhook_endpoints_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_webhook_endpoints_list_proto_rawDescData)
	})
	return file_webhook_endpoints_list_proto_rawDescData
}

var file_webhook_endpoints_list_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_webhook_endpoints_list_proto_goTypes = []interface{}{
	(*WebhookEndpointsListRequest)(nil),                      // 0: rpc.WebhookEndpointsListRequest
	(*WebhookEndpointsListResponse)(nil),                     // 1: rpc.WebhookEndpointsListResponse
	(*WebhookEndpointsListResponse_WebhookEndpointData)(nil), // 2: rpc.WebhookEndpointsListResponse.WebhookEndpointData
}
var file_webhook_endpoints_list_proto_depIdxs = []int32{
	2, // 0: rpc.WebhookEndpointsListResponse.endpoints:type_name -> rpc.WebhookEndpointsListResponse.WebhookEndpointData
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_webhook_endpoints_list_proto_init() }
func file_webhook_endpoints_list_proto_init() {
	if File_webhook_endpoints_list_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_webhook_endpoints_list_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebhookEndpointsListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webhook_endpoints_list_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebhookEndpointsListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_webhook_endpoints_list_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WebhookEndpointsListResponse_WebhookEndpointData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_webhook_endpoints_list_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_webhook_endpoints_list_proto_goTypes,
		DependencyIndexes: file_webhook_endpoints_list_proto_depIdxs,
		MessageInfos:      file_webhook_endpoints_list_proto_msgTypes,
	}.Build()
	File_webhook_endpoints_list_proto = out.File
	file_webhook_endpoints_list_proto_rawDesc = nil
	file_webhook_endpoints_list_proto_goTypes = nil
	file_webhook_endpoints_list_proto_depIdxs = nil
}
