// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.35.1
// source: pkg/plugins/proto/main.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageLevel int32

const (
	MessageLevel_INFO    MessageLevel = 0
	MessageLevel_SUCCESS MessageLevel = 1
	MessageLevel_WARNING MessageLevel = 2
	MessageLevel_ERROR   MessageLevel = 3
)

// Enum value maps for MessageLevel.
var (
	MessageLevel_name = map[int32]string{
		0: "INFO",
		1: "SUCCESS",
		2: "WARNING",
		3: "ERROR",
	}
	MessageLevel_value = map[string]int32{
		"INFO":    0,
		"SUCCESS": 1,
		"WARNING": 2,
		"ERROR":   3,
	}
)

func (x MessageLevel) Enum() *MessageLevel {
	p := new(MessageLevel)
	*p = x
	return p
}

func (x MessageLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_plugins_proto_main_proto_enumTypes[0].Descriptor()
}

func (MessageLevel) Type() protoreflect.EnumType {
	return &file_pkg_plugins_proto_main_proto_enumTypes[0]
}

func (x MessageLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageLevel.Descriptor instead.
func (MessageLevel) EnumDescriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{0}
}

type ProgressType int32

const (
	ProgressType_PROGRESS_INFO  ProgressType = 0
	ProgressType_STEP           ProgressType = 1
	ProgressType_SPINNER_START  ProgressType = 2
	ProgressType_SPINNER_UPDATE ProgressType = 3
	ProgressType_SPINNER_STOP   ProgressType = 4
)

// Enum value maps for ProgressType.
var (
	ProgressType_name = map[int32]string{
		0: "PROGRESS_INFO",
		1: "STEP",
		2: "SPINNER_START",
		3: "SPINNER_UPDATE",
		4: "SPINNER_STOP",
	}
	ProgressType_value = map[string]int32{
		"PROGRESS_INFO":  0,
		"STEP":           1,
		"SPINNER_START":  2,
		"SPINNER_UPDATE": 3,
		"SPINNER_STOP":   4,
	}
)

func (x ProgressType) Enum() *ProgressType {
	p := new(ProgressType)
	*p = x
	return p
}

func (x ProgressType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProgressType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_plugins_proto_main_proto_enumTypes[1].Descriptor()
}

func (ProgressType) Type() protoreflect.EnumType {
	return &file_pkg_plugins_proto_main_proto_enumTypes[1]
}

func (x ProgressType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProgressType.Descriptor instead.
func (ProgressType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{1}
}

type PromptType int32

const (
	PromptType_TEXT    PromptType = 0
	PromptType_CONFIRM PromptType = 1
	PromptType_SELECT  PromptType = 2
)

// Enum value maps for PromptType.
var (
	PromptType_name = map[int32]string{
		0: "TEXT",
		1: "CONFIRM",
		2: "SELECT",
	}
	PromptType_value = map[string]int32{
		"TEXT":    0,
		"CONFIRM": 1,
		"SELECT":  2,
	}
)

func (x PromptType) Enum() *PromptType {
	p := new(PromptType)
	*p = x
	return p
}

func (x PromptType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PromptType) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_plugins_proto_main_proto_enumTypes[2].Descriptor()
}

func (PromptType) Type() protoreflect.EnumType {
	return &file_pkg_plugins_proto_main_proto_enumTypes[2]
}

func (x PromptType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PromptType.Descriptor instead.
func (PromptType) EnumDescriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{2}
}

type RunCommandRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AdditionalInfo  *AdditionalInfo        `protobuf:"bytes,1,opt,name=additional_info,json=additionalInfo,proto3" json:"additional_info,omitempty"`
	Args            []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	CoreCliHelperId uint32                 `protobuf:"varint,3,opt,name=core_cli_helper_id,json=coreCliHelperId,proto3" json:"core_cli_helper_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunCommandRequest) Reset() {
	*x = RunCommandRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandRequest) ProtoMessage() {}

func (x *RunCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandRequest.ProtoReflect.Descriptor instead.
func (*RunCommandRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{0}
}

func (x *RunCommandRequest) GetAdditionalInfo() *AdditionalInfo {
	if x != nil {
		return x.AdditionalInfo
	}
	return nil
}

func (x *RunCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunCommandRequest) GetCoreCliHelperId() uint32 {
	if x != nil {
		return x.CoreCliHelperId
	}
	return 0
}

type RunCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCommandResponse) Reset() {
	*x = RunCommandResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandResponse) ProtoMessage() {}

func (x *RunCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandResponse.ProtoReflect.Descriptor instead.
func (*RunCommandResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{1}
}

type AdditionalInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IsTerminal         *IsTerminal            `protobuf:"bytes,1,opt,name=is_terminal,json=isTerminal,proto3" json:"is_terminal,omitempty"`
	TerminalDimensions *TerminalDimensions    `protobuf:"bytes,2,opt,name=terminal_dimensions,json=terminalDimensions,proto3" json:"terminal_dimensions,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AdditionalInfo) Reset() {
	*x = AdditionalInfo{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdditionalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdditionalInfo) ProtoMessage() {}

func (x *AdditionalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdditionalInfo.ProtoReflect.Descriptor instead.
func (*AdditionalInfo) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{2}
}

func (x *AdditionalInfo) GetIsTerminal() *IsTerminal {
	if x != nil {
		return x.IsTerminal
	}
	return nil
}

func (x *AdditionalInfo) GetTerminalDimensions() *TerminalDimensions {
	if x != nil {
		return x.TerminalDimensions
	}
	return nil
}

type IsTerminal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdin         bool                   `protobuf:"varint,1,opt,name=stdin,proto3" json:"stdin,omitempty"`
	Stdout        bool                   `protobuf:"varint,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        bool                   `protobuf:"varint,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsTerminal) Reset() {
	*x = IsTerminal{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsTerminal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsTerminal) ProtoMessage() {}

func (x *IsTerminal) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsTerminal.ProtoReflect.Descriptor instead.
func (*IsTerminal) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{3}
}

func (x *IsTerminal) GetStdin() bool {
	if x != nil {
		return x.Stdin
	}
	return false
}

func (x *IsTerminal) GetStdout() bool {
	if x != nil {
		return x.Stdout
	}
	return false
}

func (x *IsTerminal) GetStderr() bool {
	if x != nil {
		return x.Stderr
	}
	return false
}

type TerminalDimensions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalDimensions) Reset() {
	*x = TerminalDimensions{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalDimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalDimensions) ProtoMessage() {}

func (x *TerminalDimensions) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalDimensions.ProtoReflect.Descriptor instead.
func (*TerminalDimensions) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{4}
}

func (x *TerminalDimensions) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *TerminalDimensions) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{5}
}

func (x *EchoRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{6}
}

func (x *EchoResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type SendAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventValue    string                 `protobuf:"bytes,2,opt,name=event_value,json=eventValue,proto3" json:"event_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAnalyticsRequest) Reset() {
	*x = SendAnalyticsRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAnalyticsRequest) ProtoMessage() {}

func (x *SendAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*SendAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{7}
}

func (x *SendAnalyticsRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *SendAnalyticsRequest) GetEventValue() string {
	if x != nil {
		return x.EventValue
	}
	return ""
}

type SendAnalyticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAnalyticsResponse) Reset() {
	*x = SendAnalyticsResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAnalyticsResponse) ProtoMessage() {}

func (x *SendAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*SendAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{8}
}

type KeychainGetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeychainGetPasswordRequest) Reset() {
	*x = KeychainGetPasswordRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeychainGetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeychainGetPasswordRequest) ProtoMessage() {}

func (x *KeychainGetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeychainGetPasswordRequest.ProtoReflect.Descriptor instead.
func (*KeychainGetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{9}
}

func (x *KeychainGetPasswordRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KeychainGetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeychainGetPasswordResponse) Reset() {
	*x = KeychainGetPasswordResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeychainGetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeychainGetPasswordResponse) ProtoMessage() {}

func (x *KeychainGetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeychainGetPasswordResponse.ProtoReflect.Descriptor instead.
func (*KeychainGetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{10}
}

func (x *KeychainGetPasswordResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *KeychainGetPasswordResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type KeychainSetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeychainSetPasswordRequest) Reset() {
	*x = KeychainSetPasswordRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeychainSetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeychainSetPasswordRequest) ProtoMessage() {}

func (x *KeychainSetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeychainSetPasswordRequest.ProtoReflect.Descriptor instead.
func (*KeychainSetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{11}
}

func (x *KeychainSetPasswordRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeychainSetPasswordRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type KeychainSetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeychainSetPasswordResponse) Reset() {
	*x = KeychainSetPasswordResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeychainSetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeychainSetPasswordResponse) ProtoMessage() {}

func (x *KeychainSetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeychainSetPasswordResponse.ProtoReflect.Descriptor instead.
func (*KeychainSetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{12}
}

type KeychainDeletePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeychainDeletePasswordRequest) Reset() {
	*x = KeychainDeletePasswordRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeychainDeletePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeychainDeletePasswordRequest) ProtoMessage() {}

func (x *KeychainDeletePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeychainDeletePasswordRequest.ProtoReflect.Descriptor instead.
func (*KeychainDeletePasswordRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{13}
}

func (x *KeychainDeletePasswordRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KeychainDeletePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeychainDeletePasswordResponse) Reset() {
	*x = KeychainDeletePasswordResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeychainDeletePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeychainDeletePasswordResponse) ProtoMessage() {}

func (x *KeychainDeletePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeychainDeletePasswordResponse.ProtoReflect.Descriptor instead.
func (*KeychainDeletePasswordResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{14}
}

func (x *KeychainDeletePasswordResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type KeychainFindCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeychainFindCredentialsRequest) Reset() {
	*x = KeychainFindCredentialsRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeychainFindCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeychainFindCredentialsRequest) ProtoMessage() {}

func (x *KeychainFindCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeychainFindCredentialsRequest.ProtoReflect.Descriptor instead.
func (*KeychainFindCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{15}
}

type KeychainFindCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeychainFindCredentialsResponse) Reset() {
	*x = KeychainFindCredentialsResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeychainFindCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeychainFindCredentialsResponse) ProtoMessage() {}

func (x *KeychainFindCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeychainFindCredentialsResponse.ProtoReflect.Descriptor instead.
func (*KeychainFindCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{16}
}

func (x *KeychainFindCredentialsResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type RunPeerPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Cwd           string                 `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPeerPluginRequest) Reset() {
	*x = RunPeerPluginRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPeerPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPeerPluginRequest) ProtoMessage() {}

func (x *RunPeerPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPeerPluginRequest.ProtoReflect.Descriptor instead.
func (*RunPeerPluginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{17}
}

func (x *RunPeerPluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *RunPeerPluginRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunPeerPluginRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

type RunPeerPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPeerPluginResponse) Reset() {
	*x = RunPeerPluginResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPeerPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPeerPluginResponse) ProtoMessage() {}

func (x *RunPeerPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPeerPluginResponse.ProtoReflect.Descriptor instead.
func (*RunPeerPluginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{18}
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Level         MessageLevel           `protobuf:"varint,2,opt,name=level,proto3,enum=proto.MessageLevel" json:"level,omitempty"` // Future (milestone 4): string key = 3; map<string, string> args = 4;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{19}
}

func (x *SendMessageRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendMessageRequest) GetLevel() MessageLevel {
	if x != nil {
		return x.Level
	}
	return MessageLevel_INFO
}

type SendMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{20}
}

type OutputBlock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`       // "data", "warning", "nextstep", "error"
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // JSON-encoded payload (shape varies per type)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OutputBlock) Reset() {
	*x = OutputBlock{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OutputBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputBlock) ProtoMessage() {}

func (x *OutputBlock) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OutputBlock.ProtoReflect.Descriptor instead.
func (*OutputBlock) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{21}
}

func (x *OutputBlock) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *OutputBlock) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type SendCommandOutputRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Command       string                 `protobuf:"bytes,1,opt,name=command,proto3" json:"command,omitempty"`
	Blocks        []*OutputBlock         `protobuf:"bytes,2,rep,name=blocks,proto3" json:"blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandOutputRequest) Reset() {
	*x = SendCommandOutputRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandOutputRequest) ProtoMessage() {}

func (x *SendCommandOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandOutputRequest.ProtoReflect.Descriptor instead.
func (*SendCommandOutputRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{22}
}

func (x *SendCommandOutputRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *SendCommandOutputRequest) GetBlocks() []*OutputBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type SendCommandOutputResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendCommandOutputResponse) Reset() {
	*x = SendCommandOutputResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendCommandOutputResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendCommandOutputResponse) ProtoMessage() {}

func (x *SendCommandOutputResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendCommandOutputResponse.ProtoReflect.Descriptor instead.
func (*SendCommandOutputResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{23}
}

type SendProgressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // caller-generated, supports concurrent spinners
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Type          ProgressType           `protobuf:"varint,3,opt,name=type,proto3,enum=proto.ProgressType" json:"type,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"` // relevant on SPINNER_STOP only
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendProgressRequest) Reset() {
	*x = SendProgressRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendProgressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendProgressRequest) ProtoMessage() {}

func (x *SendProgressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendProgressRequest.ProtoReflect.Descriptor instead.
func (*SendProgressRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{24}
}

func (x *SendProgressRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SendProgressRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendProgressRequest) GetType() ProgressType {
	if x != nil {
		return x.Type
	}
	return ProgressType_PROGRESS_INFO
}

func (x *SendProgressRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SendProgressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendProgressResponse) Reset() {
	*x = SendProgressResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendProgressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendProgressResponse) ProtoMessage() {}

func (x *SendProgressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendProgressResponse.ProtoReflect.Descriptor instead.
func (*SendProgressResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{25}
}

type PromptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type          PromptType             `protobuf:"varint,2,opt,name=type,proto3,enum=proto.PromptType" json:"type,omitempty"`
	Options       []string               `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty"` // required for SELECT
	DefaultValue  string                 `protobuf:"bytes,4,opt,name=default_value,json=defaultValue,proto3" json:"default_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptRequest) Reset() {
	*x = PromptRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptRequest) ProtoMessage() {}

func (x *PromptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptRequest.ProtoReflect.Descriptor instead.
func (*PromptRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{26}
}

func (x *PromptRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PromptRequest) GetType() PromptType {
	if x != nil {
		return x.Type
	}
	return PromptType_TEXT
}

func (x *PromptRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *PromptRequest) GetDefaultValue() string {
	if x != nil {
		return x.DefaultValue
	}
	return ""
}

type PromptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"` // "true"/"false" for CONFIRM, selected value for SELECT
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PromptResponse) Reset() {
	*x = PromptResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PromptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromptResponse) ProtoMessage() {}

func (x *PromptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromptResponse.ProtoReflect.Descriptor instead.
func (*PromptResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{27}
}

func (x *PromptResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_pkg_plugins_proto_main_proto protoreflect.FileDescriptor

const file_pkg_plugins_proto_main_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/plugins/proto/main.proto\x12\x05proto\"\x94\x01\n" +
	"\x11RunCommandRequest\x12>\n" +
	"\x0fadditional_info\x18\x01 \x01(\v2\x15.proto.AdditionalInfoR\x0eadditionalInfo\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12+\n" +
	"\x12core_cli_helper_id\x18\x03 \x01(\rR\x0fcoreCliHelperId\"\x14\n" +
	"\x12RunCommandResponse\"\x90\x01\n" +
	"\x0eAdditionalInfo\x122\n" +
	"\vis_terminal\x18\x01 \x01(\v2\x11.proto.IsTerminalR\n" +
	"isTerminal\x12J\n" +
	"\x13terminal_dimensions\x18\x02 \x01(\v2\x19.proto.TerminalDimensionsR\x12terminalDimensions\"R\n" +
	"\n" +
	"IsTerminal\x12\x14\n" +
	"\x05stdin\x18\x01 \x01(\bR\x05stdin\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\bR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\bR\x06stderr\"B\n" +
	"\x12TerminalDimensions\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\"#\n" +
	"\vEchoRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\"&\n" +
	"\fEchoResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\"V\n" +
	"\x14SendAnalyticsRequest\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12\x1f\n" +
	"\vevent_value\x18\x02 \x01(\tR\n" +
	"eventValue\"\x17\n" +
	"\x15SendAnalyticsResponse\".\n" +
	"\x1aKeychainGetPasswordRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"I\n" +
	"\x1bKeychainGetPasswordResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"D\n" +
	"\x1aKeychainSetPasswordRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x1d\n" +
	"\x1bKeychainSetPasswordResponse\"1\n" +
	"\x1dKeychainDeletePasswordRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\":\n" +
	"\x1eKeychainDeletePasswordResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\" \n" +
	"\x1eKeychainFindCredentialsRequest\"5\n" +
	"\x1fKeychainFindCredentialsResponse\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys\"]\n" +
	"\x14RunPeerPluginRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\"\x17\n" +
	"\x15RunPeerPluginResponse\"Y\n" +
	"\x12SendMessageRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12)\n" +
	"\x05level\x18\x02 \x01(\x0e2\x13.proto.MessageLevelR\x05level\"\x15\n" +
	"\x13SendMessageResponse\";\n" +
	"\vOutputBlock\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"`\n" +
	"\x18SendCommandOutputRequest\x12\x18\n" +
	"\acommand\x18\x01 \x01(\tR\acommand\x12*\n" +
	"\x06blocks\x18\x02 \x03(\v2\x12.proto.OutputBlockR\x06blocks\"\x1b\n" +
	"\x19SendCommandOutputResponse\"\x82\x01\n" +
	"\x13SendProgressRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.proto.ProgressTypeR\x04type\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\"\x16\n" +
	"\x14SendProgressResponse\"\x8f\x01\n" +
	"\rPromptRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12%\n" +
	"\x04type\x18\x02 \x01(\x0e2\x11.proto.PromptTypeR\x04type\x12\x18\n" +
	"\aoptions\x18\x03 \x03(\tR\aoptions\x12#\n" +
	"\rdefault_value\x18\x04 \x01(\tR\fdefaultValue\"&\n" +
	"\x0ePromptResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value*=\n" +
	"\fMessageLevel\x12\b\n" +
	"\x04INFO\x10\x00\x12\v\n" +
	"\aSUCCESS\x10\x01\x12\v\n" +
	"\aWARNING\x10\x02\x12\t\n" +
	"\x05ERROR\x10\x03*d\n" +
	"\fProgressType\x12\x11\n" +
	"\rPROGRESS_INFO\x10\x00\x12\b\n" +
	"\x04STEP\x10\x01\x12\x11\n" +
	"\rSPINNER_START\x10\x02\x12\x12\n" +
	"\x0eSPINNER_UPDATE\x10\x03\x12\x10\n" +
	"\fSPINNER_STOP\x10\x04*/\n" +
	"\n" +
	"PromptType\x12\b\n" +
	"\x04TEXT\x10\x00\x12\v\n" +
	"\aCONFIRM\x10\x01\x12\n" +
	"\n" +
	"\x06SELECT\x10\x022I\n" +
	"\x04Main\x12A\n" +
	"\n" +
	"RunCommand\x12\x18.proto.RunCommandRequest\x1a\x19.proto.RunCommandResponse2\x83\a\n" +
	"\rCoreCLIHelper\x12/\n" +
	"\x04Echo\x12\x12.proto.EchoRequest\x1a\x13.proto.EchoResponse\x12J\n" +
	"\rSendAnalytics\x12\x1b.proto.SendAnalyticsRequest\x1a\x1c.proto.SendAnalyticsResponse\x12\\\n" +
	"\x13KeychainGetPassword\x12!.proto.KeychainGetPasswordRequest\x1a\".proto.KeychainGetPasswordResponse\x12\\\n" +
	"\x13KeychainSetPassword\x12!.proto.KeychainSetPasswordRequest\x1a\".proto.KeychainSetPasswordResponse\x12e\n" +
	"\x16KeychainDeletePassword\x12$.proto.KeychainDeletePasswordRequest\x1a%.proto.KeychainDeletePasswordResponse\x12h\n" +
	"\x17KeychainFindCredentials\x12%.proto.KeychainFindCredentialsRequest\x1a&.proto.KeychainFindCredentialsResponse\x12J\n" +
	"\rRunPeerPlugin\x12\x1b.proto.RunPeerPluginRequest\x1a\x1c.proto.RunPeerPluginResponse\x12D\n" +
	"\vSendMessage\x12\x19.proto.SendMessageRequest\x1a\x1a.proto.SendMessageResponse\x12V\n" +
	"\x11SendCommandOutput\x12\x1f.proto.SendCommandOutputRequest\x1a .proto.SendCommandOutputResponse\x12G\n" +
	"\fSendProgress\x12\x1a.proto.SendProgressRequest\x1a\x1b.proto.SendProgressResponse\x125\n" +
	"\x06Prompt\x12\x14.proto.PromptRequest\x1a\x15.proto.PromptResponseB,Z*github.com/stripe/stripe-cli/plugins/protob\x06proto3"

var (
	file_pkg_plugins_proto_main_proto_rawDescOnce sync.Once
	file_pkg_plugins_proto_main_proto_rawDescData []byte
)

func file_pkg_plugins_proto_main_proto_rawDescGZIP() []byte {
	file_pkg_plugins_proto_main_proto_rawDescOnce.Do(func() {
		file_pkg_plugins_proto_main_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugins_proto_main_proto_rawDesc), len(file_pkg_plugins_proto_main_proto_rawDesc)))
	})
	return file_pkg_plugins_proto_main_proto_rawDescData
}

var file_pkg_plugins_proto_main_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_pkg_plugins_proto_main_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_pkg_plugins_proto_main_proto_goTypes = []any{
	(MessageLevel)(0),                       // 0: proto.MessageLevel
	(ProgressType)(0),                       // 1: proto.ProgressType
	(PromptType)(0),                         // 2: proto.PromptType
	(*RunCommandRequest)(nil),               // 3: proto.RunCommandRequest
	(*RunCommandResponse)(nil),              // 4: proto.RunCommandResponse
	(*AdditionalInfo)(nil),                  // 5: proto.AdditionalInfo
	(*IsTerminal)(nil),                      // 6: proto.IsTerminal
	(*TerminalDimensions)(nil),              // 7: proto.TerminalDimensions
	(*EchoRequest)(nil),                     // 8: proto.EchoRequest
	(*EchoResponse)(nil),                    // 9: proto.EchoResponse
	(*SendAnalyticsRequest)(nil),            // 10: proto.SendAnalyticsRequest
	(*SendAnalyticsResponse)(nil),           // 11: proto.SendAnalyticsResponse
	(*KeychainGetPasswordRequest)(nil),      // 12: proto.KeychainGetPasswordRequest
	(*KeychainGetPasswordResponse)(nil),     // 13: proto.KeychainGetPasswordResponse
	(*KeychainSetPasswordRequest)(nil),      // 14: proto.KeychainSetPasswordRequest
	(*KeychainSetPasswordResponse)(nil),     // 15: proto.KeychainSetPasswordResponse
	(*KeychainDeletePasswordRequest)(nil),   // 16: proto.KeychainDeletePasswordRequest
	(*KeychainDeletePasswordResponse)(nil),  // 17: proto.KeychainDeletePasswordResponse
	(*KeychainFindCredentialsRequest)(nil),  // 18: proto.KeychainFindCredentialsRequest
	(*KeychainFindCredentialsResponse)(nil), // 19: proto.KeychainFindCredentialsResponse
	(*RunPeerPluginRequest)(nil),            // 20: proto.RunPeerPluginRequest
	(*RunPeerPluginResponse)(nil),           // 21: proto.RunPeerPluginResponse
	(*SendMessageRequest)(nil),              // 22: proto.SendMessageRequest
	(*SendMessageResponse)(nil),             // 23: proto.SendMessageResponse
	(*OutputBlock)(nil),                     // 24: proto.OutputBlock
	(*SendCommandOutputRequest)(nil),        // 25: proto.SendCommandOutputRequest
	(*SendCommandOutputResponse)(nil),       // 26: proto.SendCommandOutputResponse
	(*SendProgressRequest)(nil),             // 27: proto.SendProgressRequest
	(*SendProgressResponse)(nil),            // 28: proto.SendProgressResponse
	(*PromptRequest)(nil),                   // 29: proto.PromptRequest
	(*PromptResponse)(nil),                  // 30: proto.PromptResponse
}
var file_pkg_plugins_proto_main_proto_depIdxs = []int32{
	5,  // 0: proto.RunCommandRequest.additional_info:type_name -> proto.AdditionalInfo
	6,  // 1: proto.AdditionalInfo.is_terminal:type_name -> proto.IsTerminal
	7,  // 2: proto.AdditionalInfo.terminal_dimensions:type_name -> proto.TerminalDimensions
	0,  // 3: proto.SendMessageRequest.level:type_name -> proto.MessageLevel
	24, // 4: proto.SendCommandOutputRequest.blocks:type_name -> proto.OutputBlock
	1,  // 5: proto.SendProgressRequest.type:type_name -> proto.ProgressType
	2,  // 6: proto.PromptRequest.type:type_name -> proto.PromptType
	3,  // 7: proto.Main.RunCommand:input_type -> proto.RunCommandRequest
	8,  // 8: proto.CoreCLIHelper.Echo:input_type -> proto.EchoRequest
	10, // 9: proto.CoreCLIHelper.SendAnalytics:input_type -> proto.SendAnalyticsRequest
	12, // 10: proto.CoreCLIHelper.KeychainGetPassword:input_type -> proto.KeychainGetPasswordRequest
	14, // 11: proto.CoreCLIHelper.KeychainSetPassword:input_type -> proto.KeychainSetPasswordRequest
	16, // 12: proto.CoreCLIHelper.KeychainDeletePassword:input_type -> proto.KeychainDeletePasswordRequest
	18, // 13: proto.CoreCLIHelper.KeychainFindCredentials:input_type -> proto.KeychainFindCredentialsRequest
	20, // 14: proto.CoreCLIHelper.RunPeerPlugin:input_type -> proto.RunPeerPluginRequest
	22, // 15: proto.CoreCLIHelper.SendMessage:input_type -> proto.SendMessageRequest
	25, // 16: proto.CoreCLIHelper.SendCommandOutput:input_type -> proto.SendCommandOutputRequest
	27, // 17: proto.CoreCLIHelper.SendProgress:input_type -> proto.SendProgressRequest
	29, // 18: proto.CoreCLIHelper.Prompt:input_type -> proto.PromptRequest
	4,  // 19: proto.Main.RunCommand:output_type -> proto.RunCommandResponse
	9,  // 20: proto.CoreCLIHelper.Echo:output_type -> proto.EchoResponse
	11, // 21: proto.CoreCLIHelper.SendAnalytics:output_type -> proto.SendAnalyticsResponse
	13, // 22: proto.CoreCLIHelper.KeychainGetPassword:output_type -> proto.KeychainGetPasswordResponse
	15, // 23: proto.CoreCLIHelper.KeychainSetPassword:output_type -> proto.KeychainSetPasswordResponse
	17, // 24: proto.CoreCLIHelper.KeychainDeletePassword:output_type -> proto.KeychainDeletePasswordResponse
	19, // 25: proto.CoreCLIHelper.KeychainFindCredentials:output_type -> proto.KeychainFindCredentialsResponse
	21, // 26: proto.CoreCLIHelper.RunPeerPlugin:output_type -> proto.RunPeerPluginResponse
	23, // 27: proto.CoreCLIHelper.SendMessage:output_type -> proto.SendMessageResponse
	26, // 28: proto.CoreCLIHelper.SendCommandOutput:output_type -> proto.SendCommandOutputResponse
	28, // 29: proto.CoreCLIHelper.SendProgress:output_type -> proto.SendProgressResponse
	30, // 30: proto.CoreCLIHelper.Prompt:output_type -> proto.PromptResponse
	19, // [19:31] is the sub-list for method output_type
	7,  // [7:19] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_pkg_plugins_proto_main_proto_init() }
func file_pkg_plugins_proto_main_proto_init() {
	if File_pkg_plugins_proto_main_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugins_proto_main_proto_rawDesc), len(file_pkg_plugins_proto_main_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_plugins_proto_main_proto_goTypes,
		DependencyIndexes: file_pkg_plugins_proto_main_proto_depIdxs,
		EnumInfos:         file_pkg_plugins_proto_main_proto_enumTypes,
		MessageInfos:      file_pkg_plugins_proto_main_proto_msgTypes,
	}.Build()
	File_pkg_plugins_proto_main_proto = out.File
	file_pkg_plugins_proto_main_proto_goTypes = nil
	file_pkg_plugins_proto_main_proto_depIdxs = nil
}
