// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v7.34.0
// source: pkg/plugins/proto/main.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MainClient is the client API for Main service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MainClient interface {
	RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (*RunCommandResponse, error)
}

type mainClient struct {
	cc grpc.ClientConnInterface
}

func NewMainClient(cc grpc.ClientConnInterface) MainClient {
	return &mainClient{cc}
}

func (c *mainClient) RunCommand(ctx context.Context, in *RunCommandRequest, opts ...grpc.CallOption) (*RunCommandResponse, error) {
	out := new(RunCommandResponse)
	err := c.cc.Invoke(ctx, "/proto.Main/RunCommand", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MainServer is the server API for Main service.
// All implementations must embed UnimplementedMainServer
// for forward compatibility
type MainServer interface {
	RunCommand(context.Context, *RunCommandRequest) (*RunCommandResponse, error)
	mustEmbedUnimplementedMainServer()
}

// UnimplementedMainServer must be embedded to have forward compatible implementations.
type UnimplementedMainServer struct {
}

func (UnimplementedMainServer) RunCommand(context.Context, *RunCommandRequest) (*RunCommandResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCommand not implemented")
}
func (UnimplementedMainServer) mustEmbedUnimplementedMainServer() {}

// UnsafeMainServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MainServer will
// result in compilation errors.
type UnsafeMainServer interface {
	mustEmbedUnimplementedMainServer()
}

func RegisterMainServer(s grpc.ServiceRegistrar, srv MainServer) {
	s.RegisterService(&Main_ServiceDesc, srv)
}

func _Main_RunCommand_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCommandRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MainServer).RunCommand(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Main/RunCommand",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MainServer).RunCommand(ctx, req.(*RunCommandRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Main_ServiceDesc is the grpc.ServiceDesc for Main service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Main_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Main",
	HandlerType: (*MainServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunCommand",
			Handler:    _Main_RunCommand_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugins/proto/main.proto",
}

// CoreCLIHelperClient is the client API for CoreCLIHelper service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreCLIHelperClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	SendAnalytics(ctx context.Context, in *SendAnalyticsRequest, opts ...grpc.CallOption) (*SendAnalyticsResponse, error)
	KeychainGetPassword(ctx context.Context, in *KeychainGetPasswordRequest, opts ...grpc.CallOption) (*KeychainGetPasswordResponse, error)
	KeychainSetPassword(ctx context.Context, in *KeychainSetPasswordRequest, opts ...grpc.CallOption) (*KeychainSetPasswordResponse, error)
	KeychainDeletePassword(ctx context.Context, in *KeychainDeletePasswordRequest, opts ...grpc.CallOption) (*KeychainDeletePasswordResponse, error)
	KeychainFindCredentials(ctx context.Context, in *KeychainFindCredentialsRequest, opts ...grpc.CallOption) (*KeychainFindCredentialsResponse, error)
}

type coreCLIHelperClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreCLIHelperClient(cc grpc.ClientConnInterface) CoreCLIHelperClient {
	return &coreCLIHelperClient{cc}
}

func (c *coreCLIHelperClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, "/proto.CoreCLIHelper/Echo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreCLIHelperClient) SendAnalytics(ctx context.Context, in *SendAnalyticsRequest, opts ...grpc.CallOption) (*SendAnalyticsResponse, error) {
	out := new(SendAnalyticsResponse)
	err := c.cc.Invoke(ctx, "/proto.CoreCLIHelper/SendAnalytics", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreCLIHelperClient) KeychainGetPassword(ctx context.Context, in *KeychainGetPasswordRequest, opts ...grpc.CallOption) (*KeychainGetPasswordResponse, error) {
	out := new(KeychainGetPasswordResponse)
	err := c.cc.Invoke(ctx, "/proto.CoreCLIHelper/KeychainGetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreCLIHelperClient) KeychainSetPassword(ctx context.Context, in *KeychainSetPasswordRequest, opts ...grpc.CallOption) (*KeychainSetPasswordResponse, error) {
	out := new(KeychainSetPasswordResponse)
	err := c.cc.Invoke(ctx, "/proto.CoreCLIHelper/KeychainSetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreCLIHelperClient) KeychainDeletePassword(ctx context.Context, in *KeychainDeletePasswordRequest, opts ...grpc.CallOption) (*KeychainDeletePasswordResponse, error) {
	out := new(KeychainDeletePasswordResponse)
	err := c.cc.Invoke(ctx, "/proto.CoreCLIHelper/KeychainDeletePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreCLIHelperClient) KeychainFindCredentials(ctx context.Context, in *KeychainFindCredentialsRequest, opts ...grpc.CallOption) (*KeychainFindCredentialsResponse, error) {
	out := new(KeychainFindCredentialsResponse)
	err := c.cc.Invoke(ctx, "/proto.CoreCLIHelper/KeychainFindCredentials", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreCLIHelperServer is the server API for CoreCLIHelper service.
// All implementations must embed UnimplementedCoreCLIHelperServer
// for forward compatibility
type CoreCLIHelperServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	SendAnalytics(context.Context, *SendAnalyticsRequest) (*SendAnalyticsResponse, error)
	KeychainGetPassword(context.Context, *KeychainGetPasswordRequest) (*KeychainGetPasswordResponse, error)
	KeychainSetPassword(context.Context, *KeychainSetPasswordRequest) (*KeychainSetPasswordResponse, error)
	KeychainDeletePassword(context.Context, *KeychainDeletePasswordRequest) (*KeychainDeletePasswordResponse, error)
	KeychainFindCredentials(context.Context, *KeychainFindCredentialsRequest) (*KeychainFindCredentialsResponse, error)
	mustEmbedUnimplementedCoreCLIHelperServer()
}

// UnimplementedCoreCLIHelperServer must be embedded to have forward compatible implementations.
type UnimplementedCoreCLIHelperServer struct {
}

func (UnimplementedCoreCLIHelperServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedCoreCLIHelperServer) SendAnalytics(context.Context, *SendAnalyticsRequest) (*SendAnalyticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendAnalytics not implemented")
}
func (UnimplementedCoreCLIHelperServer) KeychainGetPassword(context.Context, *KeychainGetPasswordRequest) (*KeychainGetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeychainGetPassword not implemented")
}
func (UnimplementedCoreCLIHelperServer) KeychainSetPassword(context.Context, *KeychainSetPasswordRequest) (*KeychainSetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeychainSetPassword not implemented")
}
func (UnimplementedCoreCLIHelperServer) KeychainDeletePassword(context.Context, *KeychainDeletePasswordRequest) (*KeychainDeletePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeychainDeletePassword not implemented")
}
func (UnimplementedCoreCLIHelperServer) KeychainFindCredentials(context.Context, *KeychainFindCredentialsRequest) (*KeychainFindCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KeychainFindCredentials not implemented")
}
func (UnimplementedCoreCLIHelperServer) mustEmbedUnimplementedCoreCLIHelperServer() {}

// UnsafeCoreCLIHelperServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreCLIHelperServer will
// result in compilation errors.
type UnsafeCoreCLIHelperServer interface {
	mustEmbedUnimplementedCoreCLIHelperServer()
}

func RegisterCoreCLIHelperServer(s grpc.ServiceRegistrar, srv CoreCLIHelperServer) {
	s.RegisterService(&CoreCLIHelper_ServiceDesc, srv)
}

func _CoreCLIHelper_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreCLIHelperServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CoreCLIHelper/Echo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreCLIHelperServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreCLIHelper_SendAnalytics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendAnalyticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreCLIHelperServer).SendAnalytics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CoreCLIHelper/SendAnalytics",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreCLIHelperServer).SendAnalytics(ctx, req.(*SendAnalyticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreCLIHelper_KeychainGetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeychainGetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreCLIHelperServer).KeychainGetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CoreCLIHelper/KeychainGetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreCLIHelperServer).KeychainGetPassword(ctx, req.(*KeychainGetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreCLIHelper_KeychainSetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeychainSetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreCLIHelperServer).KeychainSetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CoreCLIHelper/KeychainSetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreCLIHelperServer).KeychainSetPassword(ctx, req.(*KeychainSetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreCLIHelper_KeychainDeletePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeychainDeletePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreCLIHelperServer).KeychainDeletePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CoreCLIHelper/KeychainDeletePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreCLIHelperServer).KeychainDeletePassword(ctx, req.(*KeychainDeletePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreCLIHelper_KeychainFindCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeychainFindCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreCLIHelperServer).KeychainFindCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.CoreCLIHelper/KeychainFindCredentials",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreCLIHelperServer).KeychainFindCredentials(ctx, req.(*KeychainFindCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreCLIHelper_ServiceDesc is the grpc.ServiceDesc for CoreCLIHelper service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreCLIHelper_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CoreCLIHelper",
	HandlerType: (*CoreCLIHelperServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _CoreCLIHelper_Echo_Handler,
		},
		{
			MethodName: "SendAnalytics",
			Handler:    _CoreCLIHelper_SendAnalytics_Handler,
		},
		{
			MethodName: "KeychainGetPassword",
			Handler:    _CoreCLIHelper_KeychainGetPassword_Handler,
		},
		{
			MethodName: "KeychainSetPassword",
			Handler:    _CoreCLIHelper_KeychainSetPassword_Handler,
		},
		{
			MethodName: "KeychainDeletePassword",
			Handler:    _CoreCLIHelper_KeychainDeletePassword_Handler,
		},
		{
			MethodName: "KeychainFindCredentials",
			Handler:    _CoreCLIHelper_KeychainFindCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/plugins/proto/main.proto",
}
