// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: pkg/plugins/proto/main.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunCommandRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AdditionalInfo  *AdditionalInfo        `protobuf:"bytes,1,opt,name=additional_info,json=additionalInfo,proto3" json:"additional_info,omitempty"`
	Args            []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	CoreCliHelperId uint32                 `protobuf:"varint,3,opt,name=core_cli_helper_id,json=coreCliHelperId,proto3" json:"core_cli_helper_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RunCommandRequest) Reset() {
	*x = RunCommandRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandRequest) ProtoMessage() {}

func (x *RunCommandRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandRequest.ProtoReflect.Descriptor instead.
func (*RunCommandRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{0}
}

func (x *RunCommandRequest) GetAdditionalInfo() *AdditionalInfo {
	if x != nil {
		return x.AdditionalInfo
	}
	return nil
}

func (x *RunCommandRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunCommandRequest) GetCoreCliHelperId() uint32 {
	if x != nil {
		return x.CoreCliHelperId
	}
	return 0
}

type RunCommandResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunCommandResponse) Reset() {
	*x = RunCommandResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCommandResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCommandResponse) ProtoMessage() {}

func (x *RunCommandResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunCommandResponse.ProtoReflect.Descriptor instead.
func (*RunCommandResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{1}
}

type PostInstallRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AdditionalInfo  *AdditionalInfo        `protobuf:"bytes,1,opt,name=additional_info,json=additionalInfo,proto3" json:"additional_info,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	PreviousVersion string                 `protobuf:"bytes,3,opt,name=previous_version,json=previousVersion,proto3" json:"previous_version,omitempty"`
	CoreCliHelperId uint32                 `protobuf:"varint,4,opt,name=core_cli_helper_id,json=coreCliHelperId,proto3" json:"core_cli_helper_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PostInstallRequest) Reset() {
	*x = PostInstallRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInstallRequest) ProtoMessage() {}

func (x *PostInstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInstallRequest.ProtoReflect.Descriptor instead.
func (*PostInstallRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{2}
}

func (x *PostInstallRequest) GetAdditionalInfo() *AdditionalInfo {
	if x != nil {
		return x.AdditionalInfo
	}
	return nil
}

func (x *PostInstallRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PostInstallRequest) GetPreviousVersion() string {
	if x != nil {
		return x.PreviousVersion
	}
	return ""
}

func (x *PostInstallRequest) GetCoreCliHelperId() uint32 {
	if x != nil {
		return x.CoreCliHelperId
	}
	return 0
}

type PostInstallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PostInstallResponse) Reset() {
	*x = PostInstallResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PostInstallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostInstallResponse) ProtoMessage() {}

func (x *PostInstallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostInstallResponse.ProtoReflect.Descriptor instead.
func (*PostInstallResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{3}
}

type PreUninstallRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	AdditionalInfo  *AdditionalInfo        `protobuf:"bytes,1,opt,name=additional_info,json=additionalInfo,proto3" json:"additional_info,omitempty"`
	Version         string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	CoreCliHelperId uint32                 `protobuf:"varint,3,opt,name=core_cli_helper_id,json=coreCliHelperId,proto3" json:"core_cli_helper_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PreUninstallRequest) Reset() {
	*x = PreUninstallRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreUninstallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreUninstallRequest) ProtoMessage() {}

func (x *PreUninstallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreUninstallRequest.ProtoReflect.Descriptor instead.
func (*PreUninstallRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{4}
}

func (x *PreUninstallRequest) GetAdditionalInfo() *AdditionalInfo {
	if x != nil {
		return x.AdditionalInfo
	}
	return nil
}

func (x *PreUninstallRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PreUninstallRequest) GetCoreCliHelperId() uint32 {
	if x != nil {
		return x.CoreCliHelperId
	}
	return 0
}

type PreUninstallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreUninstallResponse) Reset() {
	*x = PreUninstallResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreUninstallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreUninstallResponse) ProtoMessage() {}

func (x *PreUninstallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreUninstallResponse.ProtoReflect.Descriptor instead.
func (*PreUninstallResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{5}
}

type AdditionalInfo struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IsTerminal         *IsTerminal            `protobuf:"bytes,1,opt,name=is_terminal,json=isTerminal,proto3" json:"is_terminal,omitempty"`
	TerminalDimensions *TerminalDimensions    `protobuf:"bytes,2,opt,name=terminal_dimensions,json=terminalDimensions,proto3" json:"terminal_dimensions,omitempty"`
	// api_base_url, dashboard_base_url, and access_base_url carry the
	// --api-base/--dashboard-base/--access-base values the user explicitly passed
	// to the CLI, so a plugin can target the same non-default environment
	// (e.g. QA/dev) as the CLI that launched it. Each is empty when the user
	// didn't pass the corresponding flag; a plugin should fall back to its own
	// default in that case rather than treating an empty string as a host.
	ApiBaseUrl       string `protobuf:"bytes,3,opt,name=api_base_url,json=apiBaseUrl,proto3" json:"api_base_url,omitempty"`
	DashboardBaseUrl string `protobuf:"bytes,4,opt,name=dashboard_base_url,json=dashboardBaseUrl,proto3" json:"dashboard_base_url,omitempty"`
	AccessBaseUrl    string `protobuf:"bytes,5,opt,name=access_base_url,json=accessBaseUrl,proto3" json:"access_base_url,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AdditionalInfo) Reset() {
	*x = AdditionalInfo{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdditionalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdditionalInfo) ProtoMessage() {}

func (x *AdditionalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdditionalInfo.ProtoReflect.Descriptor instead.
func (*AdditionalInfo) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{6}
}

func (x *AdditionalInfo) GetIsTerminal() *IsTerminal {
	if x != nil {
		return x.IsTerminal
	}
	return nil
}

func (x *AdditionalInfo) GetTerminalDimensions() *TerminalDimensions {
	if x != nil {
		return x.TerminalDimensions
	}
	return nil
}

func (x *AdditionalInfo) GetApiBaseUrl() string {
	if x != nil {
		return x.ApiBaseUrl
	}
	return ""
}

func (x *AdditionalInfo) GetDashboardBaseUrl() string {
	if x != nil {
		return x.DashboardBaseUrl
	}
	return ""
}

func (x *AdditionalInfo) GetAccessBaseUrl() string {
	if x != nil {
		return x.AccessBaseUrl
	}
	return ""
}

type IsTerminal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stdin         bool                   `protobuf:"varint,1,opt,name=stdin,proto3" json:"stdin,omitempty"`
	Stdout        bool                   `protobuf:"varint,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	Stderr        bool                   `protobuf:"varint,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IsTerminal) Reset() {
	*x = IsTerminal{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IsTerminal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IsTerminal) ProtoMessage() {}

func (x *IsTerminal) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IsTerminal.ProtoReflect.Descriptor instead.
func (*IsTerminal) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{7}
}

func (x *IsTerminal) GetStdin() bool {
	if x != nil {
		return x.Stdin
	}
	return false
}

func (x *IsTerminal) GetStdout() bool {
	if x != nil {
		return x.Stdout
	}
	return false
}

func (x *IsTerminal) GetStderr() bool {
	if x != nil {
		return x.Stderr
	}
	return false
}

type TerminalDimensions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminalDimensions) Reset() {
	*x = TerminalDimensions{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminalDimensions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminalDimensions) ProtoMessage() {}

func (x *TerminalDimensions) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminalDimensions.ProtoReflect.Descriptor instead.
func (*TerminalDimensions) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{8}
}

func (x *TerminalDimensions) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *TerminalDimensions) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Input         string                 `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{9}
}

func (x *EchoRequest) GetInput() string {
	if x != nil {
		return x.Input
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Output        string                 `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{10}
}

func (x *EchoResponse) GetOutput() string {
	if x != nil {
		return x.Output
	}
	return ""
}

type SendAnalyticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EventName     string                 `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	EventValue    string                 `protobuf:"bytes,2,opt,name=event_value,json=eventValue,proto3" json:"event_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAnalyticsRequest) Reset() {
	*x = SendAnalyticsRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAnalyticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAnalyticsRequest) ProtoMessage() {}

func (x *SendAnalyticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAnalyticsRequest.ProtoReflect.Descriptor instead.
func (*SendAnalyticsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{11}
}

func (x *SendAnalyticsRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *SendAnalyticsRequest) GetEventValue() string {
	if x != nil {
		return x.EventValue
	}
	return ""
}

type SendAnalyticsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendAnalyticsResponse) Reset() {
	*x = SendAnalyticsResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendAnalyticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendAnalyticsResponse) ProtoMessage() {}

func (x *SendAnalyticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendAnalyticsResponse.ProtoReflect.Descriptor instead.
func (*SendAnalyticsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{12}
}

type KeychainGetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeychainGetPasswordRequest) Reset() {
	*x = KeychainGetPasswordRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeychainGetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeychainGetPasswordRequest) ProtoMessage() {}

func (x *KeychainGetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeychainGetPasswordRequest.ProtoReflect.Descriptor instead.
func (*KeychainGetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{13}
}

func (x *KeychainGetPasswordRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KeychainGetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeychainGetPasswordResponse) Reset() {
	*x = KeychainGetPasswordResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeychainGetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeychainGetPasswordResponse) ProtoMessage() {}

func (x *KeychainGetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeychainGetPasswordResponse.ProtoReflect.Descriptor instead.
func (*KeychainGetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{14}
}

func (x *KeychainGetPasswordResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *KeychainGetPasswordResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type KeychainSetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeychainSetPasswordRequest) Reset() {
	*x = KeychainSetPasswordRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeychainSetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeychainSetPasswordRequest) ProtoMessage() {}

func (x *KeychainSetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeychainSetPasswordRequest.ProtoReflect.Descriptor instead.
func (*KeychainSetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{15}
}

func (x *KeychainSetPasswordRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeychainSetPasswordRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type KeychainSetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeychainSetPasswordResponse) Reset() {
	*x = KeychainSetPasswordResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeychainSetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeychainSetPasswordResponse) ProtoMessage() {}

func (x *KeychainSetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeychainSetPasswordResponse.ProtoReflect.Descriptor instead.
func (*KeychainSetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{16}
}

type KeychainDeletePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeychainDeletePasswordRequest) Reset() {
	*x = KeychainDeletePasswordRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeychainDeletePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeychainDeletePasswordRequest) ProtoMessage() {}

func (x *KeychainDeletePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeychainDeletePasswordRequest.ProtoReflect.Descriptor instead.
func (*KeychainDeletePasswordRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{17}
}

func (x *KeychainDeletePasswordRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type KeychainDeletePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deleted       bool                   `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeychainDeletePasswordResponse) Reset() {
	*x = KeychainDeletePasswordResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeychainDeletePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeychainDeletePasswordResponse) ProtoMessage() {}

func (x *KeychainDeletePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeychainDeletePasswordResponse.ProtoReflect.Descriptor instead.
func (*KeychainDeletePasswordResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{18}
}

func (x *KeychainDeletePasswordResponse) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

// Deprecated: KeychainFindCredentials always returns an empty list. Use KeychainGetPassword to retrieve an individual password instead.
//
// Deprecated: Marked as deprecated in pkg/plugins/proto/main.proto.
type KeychainFindCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeychainFindCredentialsRequest) Reset() {
	*x = KeychainFindCredentialsRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeychainFindCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeychainFindCredentialsRequest) ProtoMessage() {}

func (x *KeychainFindCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeychainFindCredentialsRequest.ProtoReflect.Descriptor instead.
func (*KeychainFindCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{19}
}

// Deprecated: KeychainFindCredentials always returns an empty list. Use KeychainGetPassword to retrieve an individual password instead.
//
// Deprecated: Marked as deprecated in pkg/plugins/proto/main.proto.
type KeychainFindCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []string               `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeychainFindCredentialsResponse) Reset() {
	*x = KeychainFindCredentialsResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeychainFindCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeychainFindCredentialsResponse) ProtoMessage() {}

func (x *KeychainFindCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeychainFindCredentialsResponse.ProtoReflect.Descriptor instead.
func (*KeychainFindCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{20}
}

func (x *KeychainFindCredentialsResponse) GetKeys() []string {
	if x != nil {
		return x.Keys
	}
	return nil
}

type RunPeerPluginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginName    string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Args          []string               `protobuf:"bytes,2,rep,name=args,proto3" json:"args,omitempty"`
	Cwd           string                 `protobuf:"bytes,3,opt,name=cwd,proto3" json:"cwd,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPeerPluginRequest) Reset() {
	*x = RunPeerPluginRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPeerPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPeerPluginRequest) ProtoMessage() {}

func (x *RunPeerPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPeerPluginRequest.ProtoReflect.Descriptor instead.
func (*RunPeerPluginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{21}
}

func (x *RunPeerPluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *RunPeerPluginRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunPeerPluginRequest) GetCwd() string {
	if x != nil {
		return x.Cwd
	}
	return ""
}

type RunPeerPluginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunPeerPluginResponse) Reset() {
	*x = RunPeerPluginResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunPeerPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunPeerPluginResponse) ProtoMessage() {}

func (x *RunPeerPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunPeerPluginResponse.ProtoReflect.Descriptor instead.
func (*RunPeerPluginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{22}
}

type ResolveCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Livemode      bool                   `protobuf:"varint,1,opt,name=livemode,proto3" json:"livemode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCredentialsRequest) Reset() {
	*x = ResolveCredentialsRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCredentialsRequest) ProtoMessage() {}

func (x *ResolveCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCredentialsRequest.ProtoReflect.Descriptor instead.
func (*ResolveCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{23}
}

func (x *ResolveCredentialsRequest) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

type ResolveCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	StripeContext string                 `protobuf:"bytes,2,opt,name=stripe_context,json=stripeContext,proto3" json:"stripe_context,omitempty"`
	Livemode      bool                   `protobuf:"varint,3,opt,name=livemode,proto3" json:"livemode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveCredentialsResponse) Reset() {
	*x = ResolveCredentialsResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveCredentialsResponse) ProtoMessage() {}

func (x *ResolveCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveCredentialsResponse.ProtoReflect.Descriptor instead.
func (*ResolveCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{24}
}

func (x *ResolveCredentialsResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ResolveCredentialsResponse) GetStripeContext() string {
	if x != nil {
		return x.StripeContext
	}
	return ""
}

func (x *ResolveCredentialsResponse) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

type SwitchContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Livemode      bool                   `protobuf:"varint,2,opt,name=livemode,proto3" json:"livemode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchContextRequest) Reset() {
	*x = SwitchContextRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchContextRequest) ProtoMessage() {}

func (x *SwitchContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchContextRequest.ProtoReflect.Descriptor instead.
func (*SwitchContextRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{25}
}

func (x *SwitchContextRequest) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SwitchContextRequest) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

type SwitchContextResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AccountId   string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountName string                 `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Livemode    bool                   `protobuf:"varint,3,opt,name=livemode,proto3" json:"livemode,omitempty"`
	// switched is false if the user cancelled an interactive picker; in that
	// case the other fields are empty.
	Switched      bool `protobuf:"varint,4,opt,name=switched,proto3" json:"switched,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchContextResponse) Reset() {
	*x = SwitchContextResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchContextResponse) ProtoMessage() {}

func (x *SwitchContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchContextResponse.ProtoReflect.Descriptor instead.
func (*SwitchContextResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{26}
}

func (x *SwitchContextResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *SwitchContextResponse) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *SwitchContextResponse) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *SwitchContextResponse) GetSwitched() bool {
	if x != nil {
		return x.Switched
	}
	return false
}

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// timeout_seconds bounds how long Login waits for the user to complete
	// authentication. If unset or 0, it waits indefinitely, matching
	// `stripe login`.
	TimeoutSeconds int32 `protobuf:"varint,1,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{27}
}

func (x *LoginRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type LoginResponse struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	AccountId   string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	AccountName string                 `protobuf:"bytes,2,opt,name=account_name,json=accountName,proto3" json:"account_name,omitempty"`
	Livemode    bool                   `protobuf:"varint,3,opt,name=livemode,proto3" json:"livemode,omitempty"`
	// logged_in is false if the attempt was cancelled or timed out before
	// completing; in that case the other fields are empty. Calling Login
	// again starts a brand new login attempt (a new device code and browser
	// URL), not a resumption of this one.
	LoggedIn      bool `protobuf:"varint,4,opt,name=logged_in,json=loggedIn,proto3" json:"logged_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_plugins_proto_main_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_pkg_plugins_proto_main_proto_rawDescGZIP(), []int{28}
}

func (x *LoginResponse) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *LoginResponse) GetAccountName() string {
	if x != nil {
		return x.AccountName
	}
	return ""
}

func (x *LoginResponse) GetLivemode() bool {
	if x != nil {
		return x.Livemode
	}
	return false
}

func (x *LoginResponse) GetLoggedIn() bool {
	if x != nil {
		return x.LoggedIn
	}
	return false
}

var File_pkg_plugins_proto_main_proto protoreflect.FileDescriptor

const file_pkg_plugins_proto_main_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/plugins/proto/main.proto\x12\x05proto\"\x94\x01\n" +
	"\x11RunCommandRequest\x12>\n" +
	"\x0fadditional_info\x18\x01 \x01(\v2\x15.proto.AdditionalInfoR\x0eadditionalInfo\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12+\n" +
	"\x12core_cli_helper_id\x18\x03 \x01(\rR\x0fcoreCliHelperId\"\x14\n" +
	"\x12RunCommandResponse\"\xc6\x01\n" +
	"\x12PostInstallRequest\x12>\n" +
	"\x0fadditional_info\x18\x01 \x01(\v2\x15.proto.AdditionalInfoR\x0eadditionalInfo\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12)\n" +
	"\x10previous_version\x18\x03 \x01(\tR\x0fpreviousVersion\x12+\n" +
	"\x12core_cli_helper_id\x18\x04 \x01(\rR\x0fcoreCliHelperId\"\x15\n" +
	"\x13PostInstallResponse\"\x9c\x01\n" +
	"\x13PreUninstallRequest\x12>\n" +
	"\x0fadditional_info\x18\x01 \x01(\v2\x15.proto.AdditionalInfoR\x0eadditionalInfo\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12+\n" +
	"\x12core_cli_helper_id\x18\x03 \x01(\rR\x0fcoreCliHelperId\"\x16\n" +
	"\x14PreUninstallResponse\"\x88\x02\n" +
	"\x0eAdditionalInfo\x122\n" +
	"\vis_terminal\x18\x01 \x01(\v2\x11.proto.IsTerminalR\n" +
	"isTerminal\x12J\n" +
	"\x13terminal_dimensions\x18\x02 \x01(\v2\x19.proto.TerminalDimensionsR\x12terminalDimensions\x12 \n" +
	"\fapi_base_url\x18\x03 \x01(\tR\n" +
	"apiBaseUrl\x12,\n" +
	"\x12dashboard_base_url\x18\x04 \x01(\tR\x10dashboardBaseUrl\x12&\n" +
	"\x0faccess_base_url\x18\x05 \x01(\tR\raccessBaseUrl\"R\n" +
	"\n" +
	"IsTerminal\x12\x14\n" +
	"\x05stdin\x18\x01 \x01(\bR\x05stdin\x12\x16\n" +
	"\x06stdout\x18\x02 \x01(\bR\x06stdout\x12\x16\n" +
	"\x06stderr\x18\x03 \x01(\bR\x06stderr\"B\n" +
	"\x12TerminalDimensions\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\"#\n" +
	"\vEchoRequest\x12\x14\n" +
	"\x05input\x18\x01 \x01(\tR\x05input\"&\n" +
	"\fEchoResponse\x12\x16\n" +
	"\x06output\x18\x01 \x01(\tR\x06output\"V\n" +
	"\x14SendAnalyticsRequest\x12\x1d\n" +
	"\n" +
	"event_name\x18\x01 \x01(\tR\teventName\x12\x1f\n" +
	"\vevent_value\x18\x02 \x01(\tR\n" +
	"eventValue\"\x17\n" +
	"\x15SendAnalyticsResponse\".\n" +
	"\x1aKeychainGetPasswordRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"I\n" +
	"\x1bKeychainGetPasswordResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"D\n" +
	"\x1aKeychainSetPasswordRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x1d\n" +
	"\x1bKeychainSetPasswordResponse\"1\n" +
	"\x1dKeychainDeletePasswordRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\":\n" +
	"\x1eKeychainDeletePasswordResponse\x12\x18\n" +
	"\adeleted\x18\x01 \x01(\bR\adeleted\"$\n" +
	"\x1eKeychainFindCredentialsRequest:\x02\x18\x01\"9\n" +
	"\x1fKeychainFindCredentialsResponse\x12\x12\n" +
	"\x04keys\x18\x01 \x03(\tR\x04keys:\x02\x18\x01\"]\n" +
	"\x14RunPeerPluginRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x12\n" +
	"\x04args\x18\x02 \x03(\tR\x04args\x12\x10\n" +
	"\x03cwd\x18\x03 \x01(\tR\x03cwd\"\x17\n" +
	"\x15RunPeerPluginResponse\"7\n" +
	"\x19ResolveCredentialsRequest\x12\x1a\n" +
	"\blivemode\x18\x01 \x01(\bR\blivemode\"u\n" +
	"\x1aResolveCredentialsResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12%\n" +
	"\x0estripe_context\x18\x02 \x01(\tR\rstripeContext\x12\x1a\n" +
	"\blivemode\x18\x03 \x01(\bR\blivemode\"Q\n" +
	"\x14SwitchContextRequest\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x1a\n" +
	"\blivemode\x18\x02 \x01(\bR\blivemode\"\x91\x01\n" +
	"\x15SwitchContextResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12\x1a\n" +
	"\blivemode\x18\x03 \x01(\bR\blivemode\x12\x1a\n" +
	"\bswitched\x18\x04 \x01(\bR\bswitched\"7\n" +
	"\fLoginRequest\x12'\n" +
	"\x0ftimeout_seconds\x18\x01 \x01(\x05R\x0etimeoutSeconds\"\x8a\x01\n" +
	"\rLoginResponse\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12!\n" +
	"\faccount_name\x18\x02 \x01(\tR\vaccountName\x12\x1a\n" +
	"\blivemode\x18\x03 \x01(\bR\blivemode\x12\x1b\n" +
	"\tlogged_in\x18\x04 \x01(\bR\bloggedIn2\xd8\x01\n" +
	"\x04Main\x12A\n" +
	"\n" +
	"RunCommand\x12\x18.proto.RunCommandRequest\x1a\x19.proto.RunCommandResponse\x12D\n" +
	"\vPostInstall\x12\x19.proto.PostInstallRequest\x1a\x1a.proto.PostInstallResponse\x12G\n" +
	"\fPreUninstall\x12\x1a.proto.PreUninstallRequest\x1a\x1b.proto.PreUninstallResponse2\xaa\a\n" +
	"\rCoreCLIHelper\x12/\n" +
	"\x04Echo\x12\x12.proto.EchoRequest\x1a\x13.proto.EchoResponse\x12J\n" +
	"\rSendAnalytics\x12\x1b.proto.SendAnalyticsRequest\x1a\x1c.proto.SendAnalyticsResponse\x12\\\n" +
	"\x13KeychainGetPassword\x12!.proto.KeychainGetPasswordRequest\x1a\".proto.KeychainGetPasswordResponse\x12\\\n" +
	"\x13KeychainSetPassword\x12!.proto.KeychainSetPasswordRequest\x1a\".proto.KeychainSetPasswordResponse\x12e\n" +
	"\x16KeychainDeletePassword\x12$.proto.KeychainDeletePasswordRequest\x1a%.proto.KeychainDeletePasswordResponse\x12m\n" +
	"\x17KeychainFindCredentials\x12%.proto.KeychainFindCredentialsRequest\x1a&.proto.KeychainFindCredentialsResponse\"\x03\x88\x02\x01\x12J\n" +
	"\rRunPeerPlugin\x12\x1b.proto.RunPeerPluginRequest\x1a\x1c.proto.RunPeerPluginResponse\x12Y\n" +
	"\x12ResolveCredentials\x12 .proto.ResolveCredentialsRequest\x1a!.proto.ResolveCredentialsResponse\x12c\n" +
	"\x1cResolveCredentialsForAnyMode\x12 .proto.ResolveCredentialsRequest\x1a!.proto.ResolveCredentialsResponse\x12J\n" +
	"\rSwitchContext\x12\x1b.proto.SwitchContextRequest\x1a\x1c.proto.SwitchContextResponse\x122\n" +
	"\x05Login\x12\x13.proto.LoginRequest\x1a\x14.proto.LoginResponseB,Z*github.com/stripe/stripe-cli/plugins/protob\x06proto3"

var (
	file_pkg_plugins_proto_main_proto_rawDescOnce sync.Once
	file_pkg_plugins_proto_main_proto_rawDescData []byte
)

func file_pkg_plugins_proto_main_proto_rawDescGZIP() []byte {
	file_pkg_plugins_proto_main_proto_rawDescOnce.Do(func() {
		file_pkg_plugins_proto_main_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_plugins_proto_main_proto_rawDesc), len(file_pkg_plugins_proto_main_proto_rawDesc)))
	})
	return file_pkg_plugins_proto_main_proto_rawDescData
}

var file_pkg_plugins_proto_main_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_pkg_plugins_proto_main_proto_goTypes = []any{
	(*RunCommandRequest)(nil),               // 0: proto.RunCommandRequest
	(*RunCommandResponse)(nil),              // 1: proto.RunCommandResponse
	(*PostInstallRequest)(nil),              // 2: proto.PostInstallRequest
	(*PostInstallResponse)(nil),             // 3: proto.PostInstallResponse
	(*PreUninstallRequest)(nil),             // 4: proto.PreUninstallRequest
	(*PreUninstallResponse)(nil),            // 5: proto.PreUninstallResponse
	(*AdditionalInfo)(nil),                  // 6: proto.AdditionalInfo
	(*IsTerminal)(nil),                      // 7: proto.IsTerminal
	(*TerminalDimensions)(nil),              // 8: proto.TerminalDimensions
	(*EchoRequest)(nil),                     // 9: proto.EchoRequest
	(*EchoResponse)(nil),                    // 10: proto.EchoResponse
	(*SendAnalyticsRequest)(nil),            // 11: proto.SendAnalyticsRequest
	(*SendAnalyticsResponse)(nil),           // 12: proto.SendAnalyticsResponse
	(*KeychainGetPasswordRequest)(nil),      // 13: proto.KeychainGetPasswordRequest
	(*KeychainGetPasswordResponse)(nil),     // 14: proto.KeychainGetPasswordResponse
	(*KeychainSetPasswordRequest)(nil),      // 15: proto.KeychainSetPasswordRequest
	(*KeychainSetPasswordResponse)(nil),     // 16: proto.KeychainSetPasswordResponse
	(*KeychainDeletePasswordRequest)(nil),   // 17: proto.KeychainDeletePasswordRequest
	(*KeychainDeletePasswordResponse)(nil),  // 18: proto.KeychainDeletePasswordResponse
	(*KeychainFindCredentialsRequest)(nil),  // 19: proto.KeychainFindCredentialsRequest
	(*KeychainFindCredentialsResponse)(nil), // 20: proto.KeychainFindCredentialsResponse
	(*RunPeerPluginRequest)(nil),            // 21: proto.RunPeerPluginRequest
	(*RunPeerPluginResponse)(nil),           // 22: proto.RunPeerPluginResponse
	(*ResolveCredentialsRequest)(nil),       // 23: proto.ResolveCredentialsRequest
	(*ResolveCredentialsResponse)(nil),      // 24: proto.ResolveCredentialsResponse
	(*SwitchContextRequest)(nil),            // 25: proto.SwitchContextRequest
	(*SwitchContextResponse)(nil),           // 26: proto.SwitchContextResponse
	(*LoginRequest)(nil),                    // 27: proto.LoginRequest
	(*LoginResponse)(nil),                   // 28: proto.LoginResponse
}
var file_pkg_plugins_proto_main_proto_depIdxs = []int32{
	6,  // 0: proto.RunCommandRequest.additional_info:type_name -> proto.AdditionalInfo
	6,  // 1: proto.PostInstallRequest.additional_info:type_name -> proto.AdditionalInfo
	6,  // 2: proto.PreUninstallRequest.additional_info:type_name -> proto.AdditionalInfo
	7,  // 3: proto.AdditionalInfo.is_terminal:type_name -> proto.IsTerminal
	8,  // 4: proto.AdditionalInfo.terminal_dimensions:type_name -> proto.TerminalDimensions
	0,  // 5: proto.Main.RunCommand:input_type -> proto.RunCommandRequest
	2,  // 6: proto.Main.PostInstall:input_type -> proto.PostInstallRequest
	4,  // 7: proto.Main.PreUninstall:input_type -> proto.PreUninstallRequest
	9,  // 8: proto.CoreCLIHelper.Echo:input_type -> proto.EchoRequest
	11, // 9: proto.CoreCLIHelper.SendAnalytics:input_type -> proto.SendAnalyticsRequest
	13, // 10: proto.CoreCLIHelper.KeychainGetPassword:input_type -> proto.KeychainGetPasswordRequest
	15, // 11: proto.CoreCLIHelper.KeychainSetPassword:input_type -> proto.KeychainSetPasswordRequest
	17, // 12: proto.CoreCLIHelper.KeychainDeletePassword:input_type -> proto.KeychainDeletePasswordRequest
	19, // 13: proto.CoreCLIHelper.KeychainFindCredentials:input_type -> proto.KeychainFindCredentialsRequest
	21, // 14: proto.CoreCLIHelper.RunPeerPlugin:input_type -> proto.RunPeerPluginRequest
	23, // 15: proto.CoreCLIHelper.ResolveCredentials:input_type -> proto.ResolveCredentialsRequest
	23, // 16: proto.CoreCLIHelper.ResolveCredentialsForAnyMode:input_type -> proto.ResolveCredentialsRequest
	25, // 17: proto.CoreCLIHelper.SwitchContext:input_type -> proto.SwitchContextRequest
	27, // 18: proto.CoreCLIHelper.Login:input_type -> proto.LoginRequest
	1,  // 19: proto.Main.RunCommand:output_type -> proto.RunCommandResponse
	3,  // 20: proto.Main.PostInstall:output_type -> proto.PostInstallResponse
	5,  // 21: proto.Main.PreUninstall:output_type -> proto.PreUninstallResponse
	10, // 22: proto.CoreCLIHelper.Echo:output_type -> proto.EchoResponse
	12, // 23: proto.CoreCLIHelper.SendAnalytics:output_type -> proto.SendAnalyticsResponse
	14, // 24: proto.CoreCLIHelper.KeychainGetPassword:output_type -> proto.KeychainGetPasswordResponse
	16, // 25: proto.CoreCLIHelper.KeychainSetPassword:output_type -> proto.KeychainSetPasswordResponse
	18, // 26: proto.CoreCLIHelper.KeychainDeletePassword:output_type -> proto.KeychainDeletePasswordResponse
	20, // 27: proto.CoreCLIHelper.KeychainFindCredentials:output_type -> proto.KeychainFindCredentialsResponse
	22, // 28: proto.CoreCLIHelper.RunPeerPlugin:output_type -> proto.RunPeerPluginResponse
	24, // 29: proto.CoreCLIHelper.ResolveCredentials:output_type -> proto.ResolveCredentialsResponse
	24, // 30: proto.CoreCLIHelper.ResolveCredentialsForAnyMode:output_type -> proto.ResolveCredentialsResponse
	26, // 31: proto.CoreCLIHelper.SwitchContext:output_type -> proto.SwitchContextResponse
	28, // 32: proto.CoreCLIHelper.Login:output_type -> proto.LoginResponse
	19, // [19:33] is the sub-list for method output_type
	5,  // [5:19] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pkg_plugins_proto_main_proto_init() }
func file_pkg_plugins_proto_main_proto_init() {
	if File_pkg_plugins_proto_main_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_plugins_proto_main_proto_rawDesc), len(file_pkg_plugins_proto_main_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pkg_plugins_proto_main_proto_goTypes,
		DependencyIndexes: file_pkg_plugins_proto_main_proto_depIdxs,
		MessageInfos:      file_pkg_plugins_proto_main_proto_msgTypes,
	}.Build()
	File_pkg_plugins_proto_main_proto = out.File
	file_pkg_plugins_proto_main_proto_goTypes = nil
	file_pkg_plugins_proto_main_proto_depIdxs = nil
}
