// Code generated by gen_resources_cmds.go; DO NOT EDIT.

package resources

import "github.com/stripe/stripe-cli/pkg/cmd/resource"

var V1EntitlementsActiveEntitlementsList = resource.OperationSpec{
	Name:    "list",
	Path:    "/v1/entitlements/active_entitlements",
	Method:  "GET",
	Summary: "List all active entitlements",
	Params: map[string]*resource.ParamSpec{
		"customer": {
			Type:        "string",
			Description: "The ID of the customer.",
			Required:    true,
		},
		"ending_before": {
			Type:        "string",
			Description: "A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.",
		},
		"limit": {
			Type:        "integer",
			Description: "A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.",
		},
		"starting_after": {
			Type:        "string",
			Description: "A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.",
		},
	},
}

var V1EntitlementsActiveEntitlementsRetrieve = resource.OperationSpec{
	Name:    "retrieve",
	Path:    "/v1/entitlements/active_entitlements/{id}",
	Method:  "GET",
	Summary: "Retrieve an active entitlement",
}

var V1EntitlementsFeaturesCreate = resource.OperationSpec{
	Name:    "create",
	Path:    "/v1/entitlements/features",
	Method:  "POST",
	Summary: "Create a feature",
	Params: map[string]*resource.ParamSpec{
		"lookup_key": {
			Type:        "string",
			Description: "A unique key you provide as your own system identifier. This may be up to 80 characters.",
			Required:    true,
		},
		"name": {
			Type:        "string",
			Description: "The feature's name, for your own purpose, not meant to be displayable to the customer.",
			Required:    true,
		},
	},
}

var V1EntitlementsFeaturesList = resource.OperationSpec{
	Name:    "list",
	Path:    "/v1/entitlements/features",
	Method:  "GET",
	Summary: "List all features",
	Params: map[string]*resource.ParamSpec{
		"archived": {
			Type:        "boolean",
			Description: "If set, filter results to only include features with the given archive status.",
		},
		"ending_before": {
			Type:        "string",
			Description: "A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.",
		},
		"limit": {
			Type:        "integer",
			Description: "A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.",
		},
		"lookup_key": {
			Type:        "string",
			Description: "If set, filter results to only include features with the given lookup_key.",
		},
		"starting_after": {
			Type:        "string",
			Description: "A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.",
		},
	},
}

var V1EntitlementsFeaturesRetrieve = resource.OperationSpec{
	Name:    "retrieve",
	Path:    "/v1/entitlements/features/{id}",
	Method:  "GET",
	Summary: "Retrieve a feature",
}

var V1EntitlementsFeaturesUpdate = resource.OperationSpec{
	Name:    "update",
	Path:    "/v1/entitlements/features/{id}",
	Method:  "POST",
	Summary: "Updates a feature",
	Params: map[string]*resource.ParamSpec{
		"active": {
			Type:        "boolean",
			Description: "Inactive features cannot be attached to new products and will not be returned from the features list endpoint.",
		},
		"name": {
			Type:        "string",
			Description: "The feature's name, for your own purpose, not meant to be displayable to the customer.",
		},
	},
}
