// Code generated by gen_resources_cmds.go; DO NOT EDIT.

package resources

import "github.com/stripe/stripe-cli/pkg/cmd/resource"

var V1BillingCreditBalanceSummariesRetrieve = resource.OperationSpec{
	Name:    "retrieve",
	Path:    "/v1/billing/credit_balance_summary",
	Method:  "GET",
	Summary: "Retrieve the credit balance summary for a customer",
	Params: map[string]*resource.ParamSpec{
		"customer": {
			Type:        "string",
			Description: "The customer whose credit balance summary you're retrieving.",
		},
		"customer_account": {
			Type:        "string",
			Description: "The account representing the customer whose credit balance summary you're retrieving.",
		},
	},
}

var V1BillingCreditBalanceTransactionsList = resource.OperationSpec{
	Name:    "list",
	Path:    "/v1/billing/credit_balance_transactions",
	Method:  "GET",
	Summary: "List credit balance transactions",
	Params: map[string]*resource.ParamSpec{
		"ending_before": {
			Type:        "string",
			Description: "A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.",
		},
		"limit": {
			Type:        "integer",
			Description: "A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.",
		},
		"starting_after": {
			Type:        "string",
			Description: "A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.",
		},
		"credit_grant": {
			Type:        "string",
			Description: "The credit grant for which to fetch credit balance transactions.",
		},
		"customer": {
			Type:        "string",
			Description: "The customer whose credit balance transactions you're retrieving.",
		},
		"customer_account": {
			Type:        "string",
			Description: "The account representing the customer whose credit balance transactions you're retrieving.",
		},
	},
}

var V1BillingCreditBalanceTransactionsRetrieve = resource.OperationSpec{
	Name:    "retrieve",
	Path:    "/v1/billing/credit_balance_transactions/{id}",
	Method:  "GET",
	Summary: "Retrieve a credit balance transaction",
}

var V1BillingMeterEventSummariesList = resource.OperationSpec{
	Name:    "list",
	Path:    "/v1/billing/meters/{id}/event_summaries",
	Method:  "GET",
	Summary: "List billing meter event summaries",
	Params: map[string]*resource.ParamSpec{
		"end_time": {
			Type:        "integer",
			Description: "The timestamp from when to stop aggregating meter events (exclusive). Must be aligned with minute boundaries.",
			Required:    true,
			Format:      "unix-time",
		},
		"ending_before": {
			Type:        "string",
			Description: "A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.",
		},
		"limit": {
			Type:        "integer",
			Description: "A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.",
		},
		"start_time": {
			Type:        "integer",
			Description: "The timestamp from when to start aggregating meter events (inclusive). Must be aligned with minute boundaries.",
			Required:    true,
			Format:      "unix-time",
		},
		"starting_after": {
			Type:        "string",
			Description: "A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.",
		},
		"value_grouping_window": {
			Type:        "string",
			Description: "Specifies what granularity to use when generating event summaries. If not specified, a single event summary would be returned for the specified time range. For hourly granularity, start and end times must align with hour boundaries (e.g., 00:00, 01:00, ..., 23:00). For daily granularity, start and end times must align with UTC day boundaries (00:00 UTC).",
			Enum: []resource.EnumSpec{
				{Value: "day"},
				{Value: "hour"},
			},
		},
		"customer": {
			Type:        "string",
			Description: "The customer for which to fetch event summaries.",
			Required:    true,
		},
	},
}

var V1BillingAlertsDeactivate = resource.OperationSpec{
	Name:    "deactivate",
	Path:    "/v1/billing/alerts/{id}/deactivate",
	Method:  "POST",
	Summary: "Deactivate a billing alert",
}

var V1BillingAlertsList = resource.OperationSpec{
	Name:    "list",
	Path:    "/v1/billing/alerts",
	Method:  "GET",
	Summary: "List billing alerts",
	Params: map[string]*resource.ParamSpec{
		"meter": {
			Type:        "string",
			Description: "Filter results to only include alerts with the given meter.",
		},
		"starting_after": {
			Type:        "string",
			Description: "A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.",
		},
		"alert_type": {
			Type:        "string",
			Description: "Filter results to only include this type of alert.",
			Enum: []resource.EnumSpec{
				{Value: "usage_threshold"},
			},
		},
		"ending_before": {
			Type:        "string",
			Description: "A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.",
		},
		"limit": {
			Type:        "integer",
			Description: "A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.",
		},
	},
}

var V1BillingAlertsRetrieve = resource.OperationSpec{
	Name:    "retrieve",
	Path:    "/v1/billing/alerts/{id}",
	Method:  "GET",
	Summary: "Retrieve a billing alert",
}

var V1BillingAlertsCreate = resource.OperationSpec{
	Name:    "create",
	Path:    "/v1/billing/alerts",
	Method:  "POST",
	Summary: "Create a billing alert",
	Params: map[string]*resource.ParamSpec{
		"usage_threshold.recurrence": {
			Type:        "string",
			Description: "Defines how the alert will behave.",
			Required:    true,
			Enum: []resource.EnumSpec{
				{Value: "one_time"},
			},
		},
		"alert_type": {
			Type:        "string",
			Description: "The type of alert to create.",
			Required:    true,
			Enum: []resource.EnumSpec{
				{Value: "usage_threshold"},
			},
		},
		"title": {
			Type:        "string",
			Description: "The title of the alert.",
			Required:    true,
		},
		"usage_threshold.gte": {
			Type:        "integer",
			Description: "Defines the threshold value that triggers the alert.",
			Required:    true,
		},
		"usage_threshold.meter": {
			Type:        "string",
			Description: "The [Billing Meter](/api/billing/meter) ID whose usage is monitored.",
			Required:    true,
		},
	},
}

var V1BillingAlertsActivate = resource.OperationSpec{
	Name:    "activate",
	Path:    "/v1/billing/alerts/{id}/activate",
	Method:  "POST",
	Summary: "Activate a billing alert",
}

var V1BillingAlertsArchive = resource.OperationSpec{
	Name:    "archive",
	Path:    "/v1/billing/alerts/{id}/archive",
	Method:  "POST",
	Summary: "Archive a billing alert",
}

var V1BillingCreditGrantsVoidGrant = resource.OperationSpec{
	Name:    "void_grant",
	Path:    "/v1/billing/credit_grants/{id}/void",
	Method:  "POST",
	Summary: "Void a credit grant",
}

var V1BillingCreditGrantsList = resource.OperationSpec{
	Name:    "list",
	Path:    "/v1/billing/credit_grants",
	Method:  "GET",
	Summary: "List credit grants",
	Params: map[string]*resource.ParamSpec{
		"customer": {
			Type:        "string",
			Description: "Only return credit grants for this customer.",
		},
		"customer_account": {
			Type:        "string",
			Description: "Only return credit grants for this account representing the customer.",
		},
		"ending_before": {
			Type:        "string",
			Description: "A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.",
		},
		"limit": {
			Type:        "integer",
			Description: "A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.",
		},
		"starting_after": {
			Type:        "string",
			Description: "A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.",
		},
	},
}

var V1BillingCreditGrantsRetrieve = resource.OperationSpec{
	Name:    "retrieve",
	Path:    "/v1/billing/credit_grants/{id}",
	Method:  "GET",
	Summary: "Retrieve a credit grant",
}

var V1BillingCreditGrantsCreate = resource.OperationSpec{
	Name:    "create",
	Path:    "/v1/billing/credit_grants",
	Method:  "POST",
	Summary: "Create a credit grant",
	Params: map[string]*resource.ParamSpec{
		"priority": {
			Type:        "integer",
			Description: "The desired priority for applying this credit grant. If not specified, it will be set to the default value of 50. The highest priority is 0 and the lowest is 100.",
		},
		"customer": {
			Type:        "string",
			Description: "ID of the customer receiving the billing credits.",
		},
		"customer_account": {
			Type:        "string",
			Description: "ID of the account representing the customer receiving the billing credits.",
		},
		"effective_at": {
			Type:        "integer",
			Description: "The time when the billing credits become effective-when they're eligible for use. It defaults to the current timestamp if not specified.",
			Format:      "unix-time",
		},
		"amount.monetary.value": {
			Type:        "integer",
			Description: "A positive integer representing the amount of the credit grant.",
			Required:    true,
		},
		"category": {
			Type:        "string",
			Description: "The category of this credit grant. It defaults to `paid` if not specified.",
			Enum: []resource.EnumSpec{
				{Value: "paid"},
				{Value: "promotional"},
			},
		},
		"name": {
			Type:        "string",
			Description: "A descriptive name shown in the Dashboard.",
		},
		"expires_at": {
			Type:        "integer",
			Description: "The time when the billing credits expire. If not specified, the billing credits don't expire.",
			Format:      "unix-time",
		},
		"amount.monetary.currency": {
			Type:        "string",
			Description: "Three-letter [ISO code for the currency](https://stripe.com/docs/currencies) of the `value` parameter.",
			Required:    true,
			Format:      "currency",
		},
		"amount.type": {
			Type:        "string",
			Description: "The type of this amount. We currently only support `monetary` billing credits.",
			Required:    true,
			Enum: []resource.EnumSpec{
				{Value: "monetary"},
			},
		},
		"applicability_config.scope.price_type": {
			Type:        "string",
			Description: "The price type that credit grants can apply to. We currently only support the `metered` price type. Cannot be used in combination with `prices`.",
			Enum: []resource.EnumSpec{
				{Value: "metered"},
			},
		},
	},
}

var V1BillingCreditGrantsUpdate = resource.OperationSpec{
	Name:    "update",
	Path:    "/v1/billing/credit_grants/{id}",
	Method:  "POST",
	Summary: "Update a credit grant",
	Params: map[string]*resource.ParamSpec{
		"expires_at": {
			Type:        "integer",
			Description: "The time when the billing credits created by this credit grant expire. If set to empty, the billing credits never expire.",
		},
	},
}

var V1BillingCreditGrantsExpire = resource.OperationSpec{
	Name:    "expire",
	Path:    "/v1/billing/credit_grants/{id}/expire",
	Method:  "POST",
	Summary: "Expire a credit grant",
}

var V1BillingMeterEventsCreate = resource.OperationSpec{
	Name:    "create",
	Path:    "/v1/billing/meter_events",
	Method:  "POST",
	Summary: "Create a billing meter event",
	Params: map[string]*resource.ParamSpec{
		"identifier": {
			Type:        "string",
			Description: "A unique identifier for the event. If not provided, one is generated. We recommend using UUID-like identifiers. We will enforce uniqueness within a rolling period of at least 24 hours. The enforcement of uniqueness primarily addresses issues arising from accidental retries or other problems occurring within extremely brief time intervals. This approach helps prevent duplicate entries and ensures data integrity in high-frequency operations.",
		},
		"timestamp": {
			Type:        "integer",
			Description: "The time of the event. Measured in seconds since the Unix epoch. Must be within the past 35 calendar days or up to 5 minutes in the future. Defaults to current timestamp if not specified.",
			Format:      "unix-time",
		},
		"event_name": {
			Type:        "string",
			Description: "The name of the meter event. Corresponds with the `event_name` field on a meter.",
			Required:    true,
		},
	},
}

var V1BillingMeterEventAdjustmentsCreate = resource.OperationSpec{
	Name:    "create",
	Path:    "/v1/billing/meter_event_adjustments",
	Method:  "POST",
	Summary: "Create a billing meter event adjustment",
	Params: map[string]*resource.ParamSpec{
		"type": {
			Type:        "string",
			Description: "Specifies whether to cancel a single event or a range of events for a time period. Time period cancellation is not supported yet.",
			Required:    true,
			Enum: []resource.EnumSpec{
				{Value: "cancel"},
			},
		},
		"cancel.identifier": {
			Type:        "string",
			Description: "Unique identifier for the event. You can only cancel events within 24 hours of Stripe receiving them.",
		},
		"event_name": {
			Type:        "string",
			Description: "The name of the meter event. Corresponds with the `event_name` field on a meter.",
			Required:    true,
		},
	},
}

var V1BillingMetersUpdate = resource.OperationSpec{
	Name:    "update",
	Path:    "/v1/billing/meters/{id}",
	Method:  "POST",
	Summary: "Update a billing meter",
	Params: map[string]*resource.ParamSpec{
		"display_name": {
			Type:        "string",
			Description: "The meter’s name. Not visible to the customer.",
		},
	},
}

var V1BillingMetersDeactivate = resource.OperationSpec{
	Name:    "deactivate",
	Path:    "/v1/billing/meters/{id}/deactivate",
	Method:  "POST",
	Summary: "Deactivate a billing meter",
}

var V1BillingMetersReactivate = resource.OperationSpec{
	Name:    "reactivate",
	Path:    "/v1/billing/meters/{id}/reactivate",
	Method:  "POST",
	Summary: "Reactivate a billing meter",
}

var V1BillingMetersList = resource.OperationSpec{
	Name:    "list",
	Path:    "/v1/billing/meters",
	Method:  "GET",
	Summary: "List billing meters",
	Params: map[string]*resource.ParamSpec{
		"ending_before": {
			Type:        "string",
			Description: "A cursor for use in pagination. `ending_before` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, starting with `obj_bar`, your subsequent call can include `ending_before=obj_bar` in order to fetch the previous page of the list.",
		},
		"limit": {
			Type:        "integer",
			Description: "A limit on the number of objects to be returned. Limit can range between 1 and 100, and the default is 10.",
		},
		"starting_after": {
			Type:        "string",
			Description: "A cursor for use in pagination. `starting_after` is an object ID that defines your place in the list. For instance, if you make a list request and receive 100 objects, ending with `obj_foo`, your subsequent call can include `starting_after=obj_foo` in order to fetch the next page of the list.",
		},
		"status": {
			Type:        "string",
			Description: "Filter results to only include meters with the given status.",
			Enum: []resource.EnumSpec{
				{Value: "active"},
				{Value: "inactive"},
			},
		},
	},
}

var V1BillingMetersRetrieve = resource.OperationSpec{
	Name:    "retrieve",
	Path:    "/v1/billing/meters/{id}",
	Method:  "GET",
	Summary: "Retrieve a billing meter",
}

var V1BillingMetersCreate = resource.OperationSpec{
	Name:    "create",
	Path:    "/v1/billing/meters",
	Method:  "POST",
	Summary: "Create a billing meter",
	Params: map[string]*resource.ParamSpec{
		"event_name": {
			Type:        "string",
			Description: "The name of the meter event to record usage for. Corresponds with the `event_name` field on meter events.",
			Required:    true,
		},
		"event_time_window": {
			Type:        "string",
			Description: "The time window which meter events have been pre-aggregated for, if any.",
			Enum: []resource.EnumSpec{
				{Value: "day"},
				{Value: "hour"},
			},
		},
		"value_settings.event_payload_key": {
			Type:        "string",
			Description: "The key in the usage event payload to use as the value for this meter. For example, if the event payload contains usage on a `bytes_used` field, then set the event_payload_key to \"bytes_used\".",
			Required:    true,
		},
		"customer_mapping.event_payload_key": {
			Type:        "string",
			Description: "The key in the meter event payload to use for mapping the event to a customer.",
			Required:    true,
		},
		"customer_mapping.type": {
			Type:        "string",
			Description: "The method for mapping a meter event to a customer. Must be `by_id`.",
			Required:    true,
			Enum: []resource.EnumSpec{
				{Value: "by_id"},
			},
		},
		"default_aggregation.formula": {
			Type:        "string",
			Description: "Specifies how events are aggregated. Allowed values are `count` to count the number of events, `sum` to sum each event's value and `last` to take the last event's value in the window.",
			Required:    true,
			Enum: []resource.EnumSpec{
				{Value: "count"},
				{Value: "last"},
				{Value: "sum"},
			},
		},
		"display_name": {
			Type:        "string",
			Description: "The meter’s name. Not visible to the customer.",
			Required:    true,
		},
	},
}
