// Code generated by gen_resources_cmds.go; DO NOT EDIT.

package resources

import "github.com/stripe/stripe-cli/pkg/cmd/resource"

var V2BillingMeterEventAdjustmentsCreate = resource.OperationSpec{
	Name:    "create",
	Path:    "/v2/billing/meter_event_adjustments",
	Method:  "POST",
	Summary: "Create a Meter Event Adjustment",
	Params: map[string]*resource.ParamSpec{
		"cancel.identifier": {
			Type:        "string",
			Description: "Unique identifier for the event. You can only cancel events within 24 hours of Stripe receiving them.",
			Required:    true,
		},
		"event_name": {
			Type:        "string",
			Description: "The name of the meter event. Corresponds with the `event_name` field on a meter.",
			Required:    true,
		},
		"type": {
			Type:        "string",
			Description: "Specifies whether to cancel a single event or a range of events for a time period. Time period cancellation is not supported yet.",
			Required:    true,
			Enum: []resource.EnumSpec{
				{Value: "cancel"},
			},
		},
	},
}

var V2BillingMeterEventSessionsCreate = resource.OperationSpec{
	Name:    "create",
	Path:    "/v2/billing/meter_event_session",
	Method:  "POST",
	Summary: "Create a Meter Event Stream Authentication Session",
}

var V2BillingMeterEventsCreate = resource.OperationSpec{
	Name:    "create",
	Path:    "/v2/billing/meter_events",
	Method:  "POST",
	Summary: "Create a Meter Event with synchronous validation",
	Params: map[string]*resource.ParamSpec{
		"event_name": {
			Type:        "string",
			Description: "The name of the meter event. Corresponds with the `event_name` field on a meter.",
			Required:    true,
		},
		"identifier": {
			Type:        "string",
			Description: "A unique identifier for the event. If not provided, one will be generated.\nWe recommend using a globally unique identifier for this. We’ll enforce\nuniqueness within a rolling 24 hour period.",
		},
		"timestamp": {
			Type:        "string",
			Description: "The time of the event. Must be within the past 35 calendar days or up to\n5 minutes in the future. Defaults to current timestamp if not specified.",
			Format:      "date-time",
		},
	},
}
