on:
  schedule:
    - cron: '0 * * * *' # Every hour
  push:
    tags:
    - '*'
  pull_request:
    types: [opened, edited]
name: Package manager test
jobs:
  homebrew:
    runs-on: macos-latest
    steps:
      - run: bash scripts/install-test.sh homebrew
  apt:
    runs-on: ubuntu-latest
    steps:
      - run: bash scripts/install-test.sh apt
  yum:
    runs-on: ubuntu-latest
    container: ubuntu:18.04
    steps:
      - run: bash scripts/install-test.sh yum
  scoop:
    runs-on: windows-latest
    steps:
    - uses: MinoruSekine/setup-scoop@v4
    - shell: powershell
      run: bash scripts/install-test.sh scoop
  docker:
    runs-on: ubuntu-latest
    container: stripe/stripe-cli:latest
    steps:
      - run: bash scripts/install-test.sh docker
